export const UTHMAN_EDITION = {
  id: "uthman-taha-investigation",
  productionEnabled: false,
  sourceFile: "quran-uthmani.txt",
  sourceStatesProvenance: false,
  sourceHasPageNumbers: false,
  sourceHasJuz: false,
  officialPageCount: null,
  experimentalCompositionOnly: true,
  font: {
    regularFile: "UthmanTN1 Ver10_0.otf",
    boldFile: "UthmanTN1B Ver10_0.otf",
    family: "KFGQPC Uthman Taha Naskh",
    version: "0.10",
    designer: "Ashfaq Ahmad Niazi",
    vendor: "King Fahd Glorious Quran Printing Complex",
    distinctFrom: "KFGQPC Uthmanic Script HAFS",
    directUnicodeCompatibleWithSuppliedText: false,
    missingCodePoints: [
      "U+0671",
      "U+06D6",
      "U+06D7",
      "U+06D8",
      "U+06D9",
      "U+06DA",
      "U+06DB",
      "U+06DC",
      "U+06DF",
      "U+06E0",
      "U+06E2",
      "U+06E3",
      "U+06E5",
      "U+06E6",
      "U+06E8",
      "U+06EA",
      "U+06EB",
      "U+06EC",
      "U+06ED",
    ],
  },
  license: {
    webEmbedding: "not confirmed",
    selfHostedFontFace: "not confirmed",
    redistribution: "restricted",
    modification: "prohibited",
    bundle: false,
  },
} as const;
