import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolvePatienceMaterials } from '../../app/tools/khateeb-studio/engine/patienceBookGuide';
import type { BookRecord, BookSource } from '../../app/tools/khateeb-studio/engine/bookLibrary';
const corpus=process.env.QALAM_BOOK_CORPUS_DIR;
test.skip(!corpus,'Requires the supplied book corpus for full passage verification');
for(const locale of ['ur','en'] as const) test(`${locale}: public topic to saved draft, copy, backup and print`,async({page},testInfo)=>{
 const ur=locale==='ur'; const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const manifest=JSON.parse(await readFile(`${corpus}/manifest.json`,'utf8'));
 const sources:BookSource[]=manifest.sources;
 const records:BookRecord[]=(await Promise.all(sources.map(s=>readFile(`${corpus}/${s.id}.json`,'utf8').then(JSON.parse)))).flat();
 const topic=resolvePatienceMaterials(records,sources,locale);
 let authRequests=0;
 await page.route('**/api/research/auth',route=>{authRequests++;return route.fulfill({json:{authenticated:false}})});
 await page.route('**/api/khateeb/library**',route=>{
  const url=new URL(route.request().url());const op=url.searchParams.get('op');
  return route.fulfill({json:op==='topic'?topic:op==='record'?{record:records.find(r=>r.id===url.searchParams.get('id')),source:sources.find(s=>s.id===url.searchParams.get('sourceId'))}:{ready:true,sources,recordCount:2676}});
 });
 await page.goto('/tools/khateeb-studio');await page.getByRole('button',{name:ur?'اردو':'ENG',exact:true}).click();
 await page.getByRole('button',{name:ur?'کتابی ذخیرہ':'Book library',exact:true}).click();
 const guide=page.getByTestId('patience-book-guide');await expect(guide).toBeVisible();
 await guide.getByRole('combobox').selectOption('45');await guide.getByRole('button',{name:ur?'صبر کا مواد کھولیں':'Open patience material',exact:true}).click();
 await expect(guide.getByText(ur?'اصل عربی عبارت':'Original Arabic',{exact:true})).toHaveCount(6);
 expect(authRequests).toBe(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)).toBe(false);
 await guide.scrollIntoViewIfNeeded();await page.screenshot({path:testInfo.outputPath(`patience-guide-${locale}.png`)});
 await expect(guide).toContainText(ur?'نہج البلاغہ، حکمت 55؛ اس فائل کا فہرستی اندراج 109':'Nahj al-Balagha, saying 55; file entry 109');
 await guide.getByRole('button',{name:ur?'مکمل ماخذ دیکھیں':'Read full source',exact:true}).first().click();
 const dialog=page.getByRole('dialog',{name:ur?'مکمل کتابی عبارت':'Full book passage'});await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:ur?'بند کریں':'Close',exact:true}).click();
 await guide.getByRole('checkbox',{name:ur?'امید کا مرکز':'The foundation of hope',exact:true}).uncheck();
 await expect(guide.getByRole('button',{name:ur?'مکمل تیاری میری مجلس میں محفوظ کریں':'Save complete preparation to My Sermon',exact:true})).toBeDisabled();
 await guide.getByRole('checkbox',{name:ur?'امید کا مرکز':'The foundation of hope',exact:true}).check();
 await guide.getByRole('button',{name:ur?'مکمل تیاری میری مجلس میں محفوظ کریں':'Save complete preparation to My Sermon',exact:true}).click();
 const workspace=page.getByTestId('custom-sermon-workspace');await expect(workspace).toBeVisible();
 await expect(workspace.getByRole('textbox',{name:ur?'عنوان':'Title',exact:true}).last()).toHaveValue(ur?'صبر: درست موقف پر ثابت قدمی':'Patience: steadfastness in doing right');
 const stored=await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('qalam-khateeb-custom-v1:')).map(k=>JSON.parse(localStorage[k])));
 expect(stored).toHaveLength(1);expect(stored[0].bookExcerpts).toHaveLength(12);expect(stored[0].duration).toBe(45);
 await page.reload();await page.getByRole('button',{name:ur?'میری مجلس / میرا موضوع':'My sermon / my topic',exact:true}).click();
 await expect(workspace.getByText(ur?'مجلس کے محفوظ کتابی اقتباسات':'Saved book excerpts in this sermon',{exact:true})).toBeVisible();
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{(window as any).topicCopy=text}}}));
 await workspace.getByRole('button',{name:ur?'مکمل مسودہ نقل کریں':'Copy full draft',exact:true}).click();
 const copy=await page.evaluate(()=>(window as any).topicCopy);expect(copy).toContain(topic.materials[0].excerpt.paragraphs[0].text);expect(copy).toContain('sahifa-ar:supplication:28');expect(copy).toContain('وَتَوَاصَوْا بِالصَّبْرِ');
 const downloadPromise=page.waitForEvent('download');await workspace.getByRole('button',{name:ur?'محفوظ فائل بنائیں':'Export',exact:true}).click();const download=await downloadPromise;const backup=await readFile((await download.path())!);
 await workspace.getByRole('button',{name:ur?'اقتباس ہٹائیں':'Remove excerpt',exact:true}).first().click();await workspace.locator('input[type=file]').setInputFiles({name:'topic-backup.json',mimeType:'application/json',buffer:backup});
 await expect.poll(()=>page.evaluate(()=>{const id=localStorage.getItem('qalam-khateeb-custom-active-v1');return JSON.parse(localStorage.getItem(`qalam-khateeb-custom-v1:${id}`)!).bookExcerpts.length})).toBe(12);
 const versions=await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('qalam-khateeb-custom-v1:')).map(k=>JSON.parse(localStorage[k]).bookExcerpts.length));expect(versions.sort()).toEqual([11,12]);
 await page.evaluate(()=>{window.print=()=>{}});await workspace.getByRole('button',{name:ur?'مسودہ پرنٹ کریں / PDF محفوظ کریں':'Print draft / Save PDF',exact:true}).click();await page.emulateMedia({media:'print'});
 const print=page.locator('#khateeb-custom-print-area');await expect(print).toBeVisible();const printed=await print.innerText();expect(printed).toContain(topic.materials[0].excerpt.paragraphs[0].text);expect(printed).toContain(ur?'حکمت 55':'saying 55');expect(printed).toContain('وَتَوَاصَوْا بِالصَّبْرِ');
 expect((await page.pdf({path:testInfo.outputPath(`patience-${locale}.pdf`),format:'A4'})).length).toBeGreaterThan(5000);await page.emulateMedia({media:'screen'});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)).toBe(false);expect(errors).toEqual([]);
});
