/**
 * Urdu → Roman Urdu Lexicon
 * Phase 19A.23 — Deterministic dictionary overrides.
 *
 * Keys: Urdu script (exact match, case-sensitive).
 * Values: canonical Pakistani Roman Urdu.
 *
 * Priority: longest match first (multi-word phrases before single words).
 * Policy: TRANSLITERATION ONLY — no semantic translation.
 *   correct:  الحمدللہ → Alhamdulillah
 *   WRONG:    الحمدللہ → Praise be to Allah
 */

// ── Multi-word phrase dictionary (longest match first) ───────────────────────

export const PHRASE_LEXICON: [string, string][] = [
  // Islamic phrases — most important, high-frequency
  ["بسم اللہ الرحمن الرحیم",  "Bismillah ir Rahman ir Raheem"],
  ["بسم اللہ الرحمٰن الرحیم", "Bismillah ir Rahman ir Raheem"],
  ["الحمد للہ رب العالمین",   "Alhamdulillah Rabbil Aalameen"],
  ["السلام علیکم ورحمۃ اللہ", "Assalamu Alaikum wa Rahmatullah"],
  ["وعلیکم السلام",           "Wa Alaikum Assalam"],
  ["السلام علیکم",            "Assalamu Alaikum"],
  ["وعلیکم السلام ورحمۃ اللہ", "Wa Alaikum Assalam wa Rahmatullah"],
  ["جزاک اللہ خیر",           "JazakAllah Khair"],
  ["ان شاء اللہ",             "InshaAllah"],
  ["انشاءاللہ",               "InshaAllah"],
  ["ماشاء اللہ",              "MashaAllah"],
  ["ماشاءاللہ",               "MashaAllah"],
  ["الحمد للہ",               "Alhamdulillah"],
  ["الحمدللہ",                "Alhamdulillah"],
  ["اللہ اکبر",               "Allah Akbar"],
  ["لا الہ الا اللہ",          "La Ilaha Illallah"],
  ["محمد رسول اللہ",           "Muhammad Rasoolullah"],
  ["صلی اللہ علیہ وسلم",       "Sallallahu Alayhi Wa Sallam"],
  ["صلی اللہ علیہ والہ وسلم",  "Sallallahu Alayhi Wa Alihi Wa Sallam"],
  ["علیہ السلام",             "Alayhis Salam"],
  ["رضی اللہ عنہ",            "Razi Allahu Anhu"],
  ["رحمۃ اللہ علیہ",          "Rahmatullah Alaih"],
  ["استغفراللہ",              "Astaghfirullah"],
  ["سبحان اللہ",              "SubhanAllah"],
  ["جزاک اللہ",               "JazakAllah"],
  ["تبارک اللہ",              "TabarakAllah"],

  // Common Pakistani greetings
  ["آداب عرض ہے",             "Adab arz hai"],
  ["خوش آمدید",               "Khush Aamdeed"],
  ["شب بخیر",                  "Shab Bakhair"],

  // Common multi-word phrases
  ["ٹھیک ہے",                 "theek hai"],
  ["کیا حال ہے",              "kya haal hai"],
  ["کیا بات ہے",              "kya baat hai"],
  ["بہت اچھا",               "bohot achha"],
  ["کوئی بات نہیں",           "koi baat nahi"],
  ["خدا حافظ",               "Khuda Hafiz"],
  ["اللہ حافظ",               "Allah Hafiz"],
  ["ابھی نہیں",              "abhi nahi"],
  ["ٹھیک ہے",                "theek hai"],
  ["کچھ نہیں",               "kuch nahi"],
  ["بالکل ٹھیک",             "bilkul theek"],
  ["ضرور ضرور",              "zaroor zaroor"],
  ["ہاں جی",                 "haan ji"],
];

// ── Single-word dictionary ────────────────────────────────────────────────────

export const WORD_LEXICON: Record<string, string> = {
  // ── Special symbols ────────────────────────────────────────────────────────
  "ﷲ": "Allah",
  "ﷺ": "SAWW",
  "ؑ": "(as)",
  "ؓ": "(ra)",
  "ؒ": "(rh)",

  // ── Allah / Divine names ───────────────────────────────────────────────────
  "اللہ":         "Allah",
  "خدا":          "Khuda",
  "رب":           "Rabb",
  "رحمان":        "Rahman",
  "رحیم":         "Raheem",
  "حق":           "Haq",
  "قرآن":         "Quran",
  "قرآن پاک":     "Quran Pak",

  // ── Prophet names ──────────────────────────────────────────────────────────
  "محمد":         "Muhammad",
  "مصطفی":        "Mustafa",
  "احمد":         "Ahmad",
  "ابراہیم":      "Ibrahim",
  "موسی":         "Musa",
  "عیسی":         "Isa",
  "یوسف":         "Yusuf",
  "یحییٰ":        "Yahya",

  // ── Common Pakistani names ─────────────────────────────────────────────────
  "علی":          "Ali",
  "حسن":          "Hasan",
  "حسین":         "Hussain",
  "فاطمہ":        "Fatimah",
  "زہرا":         "Zahra",
  "عائشہ":        "Aisha",
  "خدیجہ":        "Khadijah",
  "مریم":         "Maryam",
  "امام":         "Imam",
  "عباس":         "Abbas",
  "زینب":         "Zainab",
  "رقیہ":         "Ruqayyah",
  "حمزہ":         "Hamza",
  "عمر":          "Umar",
  "عثمان":        "Usman",
  "ابوبکر":       "Abu Bakr",
  "طاہر":         "Tahir",
  "آصف":          "Asif",
  "رانا":         "Rana",
  "صاحب":         "Sahib",
  "صاحبہ":        "Sahiba",

  // ── Countries / cities ─────────────────────────────────────────────────────
  "پاکستان":      "Pakistan",
  "لاہور":        "Lahore",
  "کراچی":        "Karachi",
  "اسلام آباد":  "Islamabad",
  "پشاور":        "Peshawar",
  "کوئٹہ":        "Quetta",
  "ملتان":        "Multan",
  "راولپنڈی":    "Rawalpindi",
  "فیصل آباد":   "Faisalabad",
  "ہندوستان":     "Hindustan",
  "انڈیا":        "India",
  "ایران":        "Iran",
  "عراق":         "Iraq",
  "سعودی عرب":   "Saudi Arabia",
  "مکہ":          "Makkah",
  "مدینہ":        "Madinah",

  // ── Common Urdu particles / function words ─────────────────────────────────
  "میں":          "mein",
  "ہے":           "hai",
  "ہیں":          "hain",
  "ہو":           "ho",
  "تھا":          "tha",
  "تھی":          "thi",
  "تھے":          "thay",
  "گا":           "ga",
  "گی":           "gi",
  "گے":           "ge",
  "اور":          "aur",
  "کہ":           "keh",
  "کیا":          "kya",
  "نہیں":         "nahi",
  "نہ":           "na",
  "سے":           "se",
  "پر":           "par",
  "کو":           "ko",
  "کی":           "ki",
  "کے":           "ke",
  "کا":           "ka",
  "نے":           "ne",
  "یہ":           "yeh",
  "وہ":           "woh",
  "اس":           "is",
  "اسے":          "usay",
  "اسی":          "usi",
  "ان":           "un",
  "انہیں":        "unhain",
  "جو":           "jo",
  "تو":           "toh",
  "تب":           "tab",
  "جب":           "jab",
  "بھی":          "bhi",
  "ہی":           "hi",
  "تک":           "tak",
  "لیے":          "liye",
  "ساتھ":         "saath",
  "پھر":          "phir",
  "اب":           "ab",
  "ابھی":         "abhi",
  "کبھی":         "kabhi",
  "ہاں":          "haan",
  "بلکہ":         "balkay",
  "لیکن":         "lekin",
  "مگر":          "magar",
  "اگر":          "agar",
  "کیونکہ":       "kyunkeh",
  "یا":           "ya",
  "جیسا":         "jaisa",
  "جیسی":         "jaisi",
  "جیسے":         "jaisay",
  "ویسا":         "waisa",
  "ایسا":         "aisa",
  "ایسی":         "aisi",
  "ایسے":         "aisay",
  "کون":          "kaun",
  "کیوں":         "kyun",
  "کہاں":         "kahan",
  "کیسے":         "kaisay",
  "کتنا":         "kitna",
  "کتنی":         "kitni",
  "کتنے":         "kitnay",
  "کوئی":         "koi",
  "کچھ":          "kuch",
  "سب":           "sab",
  "ہر":           "har",
  "اپنا":         "apna",
  "اپنی":         "apni",
  "اپنے":         "apnay",
  "میرا":         "mera",
  "میری":         "meri",
  "میرے":         "meray",
  "تمہارا":       "tumhara",
  "تمہاری":       "tumhari",
  "ہمارا":        "hamara",
  "ہماری":        "hamari",
  "آپ":           "aap",
  "آپ کا":        "aap ka",
  "تم":           "tum",
  "ہم":           "hum",
  "مجھے":         "mujhe",
  "تمہیں":        "tumhain",
  "ہمیں":         "hamein",
  "مجھ":          "mujh",
  "جی":           "ji",
  "بھئی":         "bhai",

  // ── Common everyday nouns ──────────────────────────────────────────────────
  "گھر":          "ghar",
  "کام":          "kaam",
  "وقت":          "waqt",
  "دن":           "din",
  "رات":          "raat",
  "بات":          "baat",
  "جگہ":          "jagah",
  "نام":          "naam",
  "لوگ":          "log",
  "شخص":          "shakhs",
  "آدمی":         "aadmi",
  "عورت":         "aurat",
  "بچہ":          "bacha",
  "بچے":          "bachay",
  "دوست":         "dost",
  "بھائی":        "bhai",
  "بہن":          "behan",
  "ماں":          "maa",
  "باپ":          "baap",
  "امی":          "ammi",
  "ابو":          "abbu",
  "ابی":          "abi",
  "والدہ":        "walida",
  "والد":         "walid",
  "بیٹا":         "beta",
  "بیٹی":         "beti",
  "پانی":         "paani",
  "کھانا":        "khana",
  "دل":           "dil",
  "آنکھ":         "aankh",
  "ہاتھ":         "haath",
  "سر":           "sar",
  "دروازہ":       "darwaza",
  "کمرہ":         "kamra",
  "کتاب":         "kitab",
  "قلم":          "qalam",
  "کاغذ":         "kaghaz",
  "پیسہ":         "paisa",
  "کار":          "car",
  "گاڑی":         "gaari",
  "بس":           "bus",
  "راستہ":        "rasta",
  "سڑک":          "sarak",
  "شہر":          "shehar",
  "گاؤں":         "gaon",
  "ملک":          "mulk",
  "دنیا":         "duniya",
  "زمین":         "zameen",
  "آسمان":        "aasman",
  "سورج":         "suraj",
  "چاند":         "chaand",
  "ستارہ":        "sitara",
  "درخت":         "darakht",
  "پھول":         "phool",
  "پھل":          "phal",
  "بارش":         "baarish",
  "موسم":         "mausam",
  "ہوا":          "hawa",
  "آگ":           "aag",
  "پتھر":         "pathar",
  "سونا":         "sona",
  "کپڑا":         "kapra",
  "رنگ":          "rang",
  "خوشبو":        "khushbu",
  "آواز":         "aawaz",
  "خبر":          "khabar",
  "اخبار":        "akhbaar",
  "تصویر":        "tasveer",
  "کہانی":        "kahani",
  "نظم":          "nazm",
  "شعر":          "sher",
  "محبت":         "mohabbat",
  "عشق":          "ishq",
  "دوستی":        "dosti",
  "خوشی":         "khushi",
  "غم":           "gham",
  "زندگی":        "zindagi",
  "موت":          "maut",
  "صحت":          "sehat",
  "بیماری":       "bimari",
  "دوا":          "dawa",
  "ڈاکٹر":        "doctor",
  "اسپتال":       "aspatal",
  "اسکول":        "school",
  "استاد":        "ustad",
  "طالب علم":     "talib ilm",
  "علم":          "ilm",
  "دفتر":         "daftar",
  "نوکری":        "naukri",
  "تجارت":        "tijarat",
  "حکومت":        "hukumat",
  "قانون":        "qanoon",
  "عدالت":        "adalat",

  // ── Common adjectives ──────────────────────────────────────────────────────
  "اچھا":         "achha",
  "اچھی":         "achhi",
  "اچھے":         "achhe",
  "برا":          "bura",
  "بری":          "buri",
  "بڑا":          "barra",
  "بڑی":          "barri",
  "چھوٹا":        "chhota",
  "چھوٹی":        "chhoti",
  "نیا":          "naya",
  "نئی":          "nayi",
  "پرانا":        "purana",
  "پرانی":        "purani",
  "خوبصورت":      "khoobsurat",
  "خوب":          "khoob",
  "سفید":         "safaid",
  "کالا":         "kala",
  "سرخ":          "surkh",
  "سبز":          "sabz",
  "نیلا":         "neela",
  "پیلا":         "peela",
  "مشہور":        "mashhoor",
  "مشکل":         "mushkil",
  "آسان":         "aasaan",
  "ضروری":        "zaroori",
  "اہم":          "aham",
  "خوش":          "khush",
  "ناخوش":        "nakhush",
  "تھکا":         "thaka",
  "بیمار":        "beemar",
  "تندرست":       "tandrust",
  "امیر":         "ameer",
  "غریب":         "ghareeb",
  "صحیح":         "sahih",
  "غلط":          "ghalat",
  "تیز":          "taiz",
  "سست":          "sust",
  "گرم":          "garam",
  "ٹھنڈا":        "thanda",
  "لمبا":         "lamba",
  "موٹا":         "mota",
  "پتلا":         "patla",

  // ── Common verbs (root forms) ──────────────────────────────────────────────
  "ہونا":         "hona",
  "کرنا":         "karna",
  "جانا":         "jana",
  "آنا":          "aana",
  "دیکھنا":       "dekhna",
  "سننا":         "sunna",
  "بولنا":        "bolna",
  "لکھنا":        "likhna",
  "پڑھنا":        "parhna",
  "پینا":         "peena",
  "اٹھنا":        "uthna",
  "بیٹھنا":       "baithna",
  "چلنا":         "chalna",
  "دوڑنا":        "daurna",
  "کھیلنا":       "khelna",
  "ہنسنا":        "hansna",
  "رونا":         "rona",
  "ملنا":         "milna",
  "بتانا":        "batana",
  "سمجھنا":       "samajhna",
  "دینا":         "dena",
  "لینا":         "lena",
  "رکھنا":        "rakhna",
  "نکلنا":        "nikalna",
  "پہنچنا":       "pahunchna",
  "مانگنا":       "mangna",
  "خریدنا":       "kharidna",
  "بیچنا":        "bechna",
  "ہوگا":         "hoga",
  "ہوگی":         "hogi",
  "ہوں":          "hoon",

  // ── Common adverbs ─────────────────────────────────────────────────────────
  "بہت":          "bohot",
  "کافی":         "kaafi",
  "تھوڑا":        "thora",
  "تھوڑی":        "thori",
  "بالکل":        "bilkul",
  "اکثر":         "aksar",
  "کبھی کبھی":    "kabhi kabhi",
  "ہمیشہ":        "hamesha",
  "کبھی نہیں":    "kabhi nahi",
  "پہلے":         "pehle",
  "بعد میں":      "baad mein",
  "جلدی":         "jaldi",
  "آہستہ":        "aahista",
  "کل":           "kal",
  "آج":           "aaj",
  "پرسوں":        "parson",
  "یہاں":         "yahan",
  "وہاں":         "wahan",
  "اندر":         "andar",
  "باہر":         "bahar",
  "اوپر":         "upar",
  "نیچے":         "neeche",
  "سامنے":        "saamne",
  "پیچھے":        "peechhe",
  "پاس":          "paas",
  "دور":          "door",
  "قریب":         "qareeb",

  // ── Additional common words ────────────────────────────────────────────────
  "جاؤ":          "jao",
  "آرام":         "aaram",
  "کرو":          "karo",
  "بند":          "band",
  "بھیج":         "bhej",
  "بھیجو":        "bhejo",
  "روپے":         "rupay",
  "روپیہ":        "rupya",
  "دو":           "do",
  "لو":           "lo",
  "آؤ":           "aao",
  "جاو":          "jao",
  "دیکھو":        "dekho",
  "سنو":          "suno",
  "بتاؤ":         "batao",
  "لاؤ":          "lao",
  "رکو":          "ruko",
  "چلو":          "chalo",
  "ہو جاؤ":       "ho jao",
  "کر لو":        "kar lo",

  "۔": ".",
  "،": ",",
  "؟": "?",
  "!": "!",
  "؛": ";",
};

// ── Phase 19A.24: Priority name dictionary ───────────────────────────────────
// These override character-level transliteration for proper nouns.
// Sorted longest-first for prefix matching.
export const NAME_LEXICON: Record<string, string> = {
  // Prophet names
  "محمد":    "Muhammad",
  "احمد":    "Ahmad",
  "مصطفیٰ":  "Mustafa",
  "مصطفی":   "Mustafa",
  // Imams / religious figures
  "علی":     "Ali",
  "حسن":     "Hasan",
  "حسین":    "Hussain",
  "فاطمہ":   "Fatimah",
  "زہرا":    "Zahra",
  "زینب":    "Zainab",
  "عباس":    "Abbas",
  "ابراہیم": "Ibrahim",
  "موسیٰ":   "Musa",
  "موسی":    "Musa",
  "عیسیٰ":   "Isa",
  "عیسی":    "Isa",
  "یوسف":    "Yusuf",
  "یحییٰ":   "Yahya",
  "عائشہ":   "Aisha",
  "خدیجہ":   "Khadijah",
  "مریم":    "Maryam",
  "حمزہ":    "Hamza",
  "عمر":     "Umar",
  "عثمان":   "Usman",
  // Common Pakistani names
  "رانا":    "Rana",
  "طاہر":    "Tahir",
  "آصف":     "Asif",
  "سجاد":    "Sajjad",
  "آفتاب":   "Aftab",
  "خالد":    "Khalid",
  "ریحان":   "Rehan",
  "نوید":    "Naveed",
  "عمران":   "Imran",
  "کامران":  "Kamran",
  "صفیہ":    "Safia",
  "سمیرا":   "Samira",
  "نادیہ":   "Nadia",
};


// Sort phrase lexicon by length descending (longest match first)
PHRASE_LEXICON.sort((a, b) => b[0].length - a[0].length);
