/**
 * Qalam Roman Urdu Lexicon
 * Maps Roman Urdu spellings → one or more Urdu-script candidates (ranked).
 * The first candidate is the most common output.
 *
 * Principles:
 * - "main" = میں (pronoun), not مین
 * - "to" = تو (emphatic/conjunctive), not English "to"
 * - "is" = اس (demonstrative), not English "is"
 * - "par" = پر (on/but), not English
 * - "bus" = بس (just/enough)
 * - "na" = نہ / نا (don't/tag question)
 * - All spelling variants collected from corpus
 */

export type UrduCandidates = [string, ...string[]]; // at least one

export const LEXICON: Record<string, UrduCandidates> = {
  // ── Pronouns & demonstratives ────────────────────────────────────────────
  "main":     ["میں"],
  "mein":     ["میں"],
  "mai":      ["میں"],
  "mujhe":    ["مجھے"],
  "mujhy":    ["مجھے"],
  "mujhay":   ["مجھے"],
  "mujhse":   ["مجھ سے"],
  "meri":     ["میری"],
  "mery":     ["میرے"],
  "mere":     ["میرے"],
  "mera":     ["میرا"],
  "hum":      ["ہم"],
  "hamen":    ["ہمیں"],
  "hamara":   ["ہمارا"],
  "hamari":   ["ہماری"],
  "tum":      ["تم"],
  "tumhara":  ["تمہارا"],
  "tumhari":  ["تمہاری"],
  "tumhare":  ["تمہارے"],
  "tumhe":    ["تمہیں"],
  "teri":     ["تیری"],
  "tera":     ["تیرا"],
  "tere":     ["تیرے"],
  "tu":       ["تو"],
  "ap":       ["آپ"],
  "aap":      ["آپ"],
  "apna":     ["اپنا"],
  "apni":     ["اپنی"],
  "apne":     ["اپنے"],
  "apke":     ["آپ کے"],
  "apko":     ["آپ کو"],
  "woh":      ["وہ"],
  "wo":       ["وہ"],
  "uski":     ["اس کی"],
  "uska":     ["اس کا"],
  "uske":     ["اس کے"],
  "unka":     ["ان کا"],
  "unki":     ["ان کی"],
  "unke":     ["ان کے"],
  "unhe":     ["انہیں"],
  "yeh":      ["یہ"],
  "ye":       ["یہ"],
  "is":       ["اس"],
  "iss":      ["اس"],
  "in":       ["ان"],
  "wahan":    ["وہاں"],
  "wahaan":   ["وہاں"],
  "yahan":    ["یہاں"],
  "koi":      ["کوئی"],
  "kuch":     ["کچھ"],
  "sab":      ["سب"],
  "kya":      ["کیا"],
  "kia":      ["کیا"],

  // ── Verbs — common forms ─────────────────────────────────────────────────
  "hai":      ["ہے"],
  "hain":     ["ہیں"],
  "tha":      ["تھا"],
  "thi":      ["تھی"],
  "the":      ["تھے"],
  "ho":       ["ہو"],
  "hoga":     ["ہوگا"],
  "hogi":     ["ہوگی"],
  "hoge":     ["ہوگے"],
  "hojayega": ["ہو جائے گا"],
  "ho gaya":  ["ہو گیا"],
  "hogaya":   ["ہو گیا"],
  "gaya":     ["گیا"],
  "gayi":     ["گئی"],
  "gaye":     ["گئے"],
  "aaya":     ["آیا"],
  "aya":      ["آیا"],
  "aayi":     ["آئی"],
  "aaye":     ["آئے"],
  "aaoge":    ["آؤگے"],
  "aao":      ["آؤ"],
  "aajao":    ["آ جاؤ"],
  "aata":     ["آتا"],
  "ati":      ["آتی"],
  "aate":     ["آتے"],
  "jana":     ["جانا"],
  "jane":     ["جانے"],
  "jao":      ["جاؤ"],
  "jata":     ["جاتا"],
  "jati":     ["جاتی"],
  "jate":     ["جاتے"],
  "kar":      ["کر"],
  "karo":     ["کرو"],
  "karna":    ["کرنا"],
  "karta":    ["کرتا"],
  "karti":    ["کرتی"],
  "karte":    ["کرتے"],
  "kiya":     ["کیا"],
  "ki":       ["کی", "کی"],
  "karein":   ["کریں"],
  "lia":      ["لیا"],
  "liya":     ["لیا"],
  "lena":     ["لینا"],
  "lo":       ["لو"],
  "lao":      ["لاؤ"],
  "le":       ["لے"],
  "leke":     ["لے کے"],
  "dena":     ["دینا"],
  "deni":     ["دینی"],
  "do":       ["دو"],
  "diya":     ["دیا"],
  "diye":     ["دیے"],
  "raha":     ["رہا"],
  "rahi":     ["رہی"],
  "rahe":     ["رہے"],
  "rehna":    ["رہنا"],
  "sona":     ["سونا"],
  "uthna":    ["اٹھنا"],
  "parh":     ["پڑھ"],
  "parhna":   ["پڑھنا"],
  "parha":    ["پڑھا"],
  "seekha":   ["سیکھا"],
  "seekhna":  ["سیکھنا"],
  "samajh":   ["سمجھ"],
  "samjna":   ["سمجھنا"],
  "samjha":   ["سمجھا"],
  "samjhe":   ["سمجھے"],
  "samjho":   ["سمجھو"],
  "smjha":    ["سمجھا"],
  "smjho":    ["سمجھو"],
  "sun":      ["سن"],
  "suno":     ["سنو"],
  "sunta":    ["سنتا"],
  "suni":     ["سنی"],
  "bol":      ["بول"],
  "bolo":     ["بولو"],
  "kaho":     ["کہو"],
  "kaha":     ["کہا"],
  "batao":    ["بتاؤ"],
  "bataya":   ["بتایا"],
  "batana":   ["بتانا"],
  "rakh":     ["رکھ"],
  "rakhna":   ["رکھنا"],
  "rakho":    ["رکھو"],
  "poochna":  ["پوچھنا"],
  "poocha":   ["پوچھا"],
  "poocho":   ["پوچھو"],
  "khana":    ["کھانا"],
  "kha":      ["کھا"],
  "khao":     ["کھاؤ"],
  "pi":       ["پی"],
  "pina":     ["پینا"],
  "pilo":     ["پی لو"],
  "dekh":     ["دیکھ"],
  "dekho":    ["دیکھو"],
  "dekha":    ["دیکھا"],
  "dekhna":   ["دیکھنا"],
  "chalte":   ["چلتے"],
  "chalo":    ["چلو"],
  "chal":     ["چل"],
  "nikalte":  ["نکلتے"],
  "nikal":    ["نکال"],
  "milna":    ["ملنا"],
  "milte":    ["ملتے"],
  "milenge":  ["ملیں گے"],
  "mila":     ["ملا"],
  "milti":    ["ملتی"],
  "pohonch":  ["پہنچ"],
  "pohoncha": ["پہنچا"],
  "smbhalo":  ["سنبھالو"],
  "sudheray": ["سدھرے"],
  "bhool":    ["بھول"],
  "bhoolna":  ["بھولنا"],
  "bhool gaya":["بھول گیا"],
  "chutti":   ["چھٹی"],
  "likh":     ["لکھ"],
  "likho":    ["لکھو"],
  "likhna":   ["لکھنا"],

  // ── Common adjectives ────────────────────────────────────────────────────
  "acha":     ["اچھا"],
  "achha":    ["اچھا"],
  "aachi":    ["اچھی"],
  "accha":    ["اچھا"],
  "bura":     ["برا"],
  "buri":     ["بری"],
  "theek":    ["ٹھیک"],
  "thek":     ["ٹھیک"],
  "theek hai":["ٹھیک ہے"],
  "naya":     ["نیا"],
  "nayi":     ["نئی"],
  "naye":     ["نئے"],
  "pehla":    ["پہلا"],
  "pehli":    ["پہلی"],
  "pehle":    ["پہلے"],
  "dosra":    ["دوسرا"],
  "dosri":    ["دوسری"],
  "dosre":    ["دوسرے"],
  "dosron":   ["دوسروں"],
  "bada":     ["بڑا"],
  "bara":     ["بڑا"],
  "bari":     ["بڑی"],
  "chota":    ["چھوٹا"],
  "zyada":    ["زیادہ"],
  "ziada":    ["زیادہ"],
  "thoda":    ["تھوڑا"],
  "thori":    ["تھوڑی"],
  "thora":    ["تھوڑا"],
  "mushkil":  ["مشکل"],
  "asaan":    ["آسان"],
  "mashhoor": ["مشہور"],
  "garam":    ["گرم"],
  "thanda":   ["ٹھنڈا"],
  "sardi":    ["سردی"],
  "ajeeb":    ["عجیب"],
  "poora":    ["پورا"],
  "aik":      ["ایک"],
  "ek":       ["ایک"],

  // ── Adverbs, particles, conjunctions ────────────────────────────────────
  "aaj":      ["آج"],
  "kal":      ["کل"],       // yesterday OR tomorrow — context-dependent
  "abhi":     ["ابھی"],
  "ab":       ["اب"],
  "phir":     ["پھر"],
  "phr":      ["پھر"],
  "baad":     ["بعد"],
  "raat":     ["رات"],
  "subah":    ["صبح"],
  "subha":    ["صبح"],
  "roz":      ["روز"],
  "kabhi":    ["کبھی"],
  "jab":      ["جب"],
  "tab":      ["تب"],
  "jahan":    ["جہاں"],
  "kahan":    ["کہاں"],
  "kab":      ["کب"],
  "kyun":     ["کیوں"],
  "kitna":    ["کتنا"],
  "kaafi":    ["کافی"],
  "bilkul":   ["بالکل"],
  "haan":     ["ہاں"],
  "han":      ["ہاں"],
  "nahi":     ["نہیں"],
  "nhi":      ["نہیں"],
  "nahin":    ["نہیں"],
  "na":       ["نہ", "نا"],
  "mat":      ["مت"],
  "maat":     ["مت"],
  "bhi":      ["بھی"],
  "hi":       ["ہی"],
  "to":       ["تو"],
  "par":      ["پر"],
  "pe":       ["پر"],
  "se":       ["سے"],
  "ke":       ["کے"],
  "ka":       ["کا"],
  "ne":       ["نے"],
  "ko":       ["کو"],
  "tak":      ["تک"],
  "wala":     ["والا"],
  "wali":     ["والی"],
  "wale":     ["والے"],
  "walay":    ["والے"],
  "aur":      ["اور"],
  "lekin":    ["لیکن"],
  "magar":    ["مگر"],
  "agar":     ["اگر"],
  "agr":      ["اگر"],
  "phir bhi": ["پھر بھی"],
  "kyunke":   ["کیونکہ"],
  "taake":    ["تاکہ"],
  "jo":       ["جو"],
  "jis":      ["جس"],
  "jitna":    ["جتنا"],
  "bus":      ["بس"],
  "sirf":     ["صرف"],
  "zaroor":   ["ضرور"],
  "zaruri":   ["ضروری"],
  "zaroori":  ["ضروری"],
  "shayad":   ["شاید"],

  // ── Nouns — everyday ────────────────────────────────────────────────────
  "ghar":     ["گھر"],
  "kaam":     ["کام"],
  "waqt":     ["وقت"],
  "baat":     ["بات"],
  "naam":     ["نام"],
  "din":      ["دن"],
  "banda":    ["بندہ"],
  "log":      ["لوگ"],
  "dost":     ["دوست"],
  "yaar":     ["یار"],
  "bhai":     ["بھائی"],
  "bhayi":    ["بھائی"],
  "amma":     ["اماں"],
  "aama":     ["اماں"],
  "abbu":     ["ابو"],
  "mama":     ["ماما"],
  "nana":     ["نانا"],
  "makan":    ["مکان"],
  "kiraya":   ["کرایہ"],
  "pani":     ["پانی"],
  "chai":     ["چائے"],
  "sabzi":    ["سبزی"],
  "dukan":    ["دکان"],
  "gaari":    ["گاڑی"],
  "baazar":   ["بازار"],
  "bazar":    ["بازار"],
  "safar":    ["سفر"],
  "parhai":   ["پڑھائی"],
  "neend":    ["نیند"],
  "bhook":    ["بھوک"],
  "tabiyat":  ["طبیعت"],
  "mariz":    ["مریض"],
  "rishta":   ["رشتہ"],
  "shaadi":   ["شادی"],
  "rishtedaar":["رشتہ دار"],
  "kapray":   ["کپڑے"],
  "bijli":    ["بجلی"],
  "school":   ["school"],
  "dua":      ["دعا"],
  "khushi":   ["خوشی"],
  "ghussa":   ["غصہ"],
  "pareshani":["پریشانی"],
  "zindagi":  ["زندگی"],
  "zindgi":   ["زندگی"],
  "dil":      ["دل"],
  "masla":    ["مسئلہ"],
  "maslay":   ["مسائل"],
  "nateeja":  ["نتیجہ"],
  "mehnat":   ["محنت"],
  "tasveer":  ["تصویر"],

  // ── Greetings / phrases ──────────────────────────────────────────────────
  "shukriya": ["شکریہ"],
  "shukar":   ["شکر"],
  "shukra":   ["شکریہ"],
  "thnx":     ["thnx"],
  "inshaAllah":["انشاءاللہ"],
  "inshallah":["انشاءاللہ"],
  "mashAllah":["ماشاءاللہ"],
  "alhamdulillah":["الحمدللہ"],
  "jee":      ["جی"],
  "ji":       ["جی"],
  "toba":     ["توبہ"],
  "yarr":     ["یار"],

  "peeni":     ["پینی"],
  "bhejo":     ["بھیجو"],
  "chahay":     ["چاہے"],
  "chahiye":     ["چاہیے"],
  "chaye":     ["چاہیے"],
  "itna":     ["اتنا"],
  "itni":     ["اتنی"],
  "itne":     ["اتنے"],
  "gal":     ["گل"],
  "lagta":     ["لگتا"],
  "lagti":     ["لگتی"],
  "lagte":     ["لگتے"],
  "marzi":     ["مرضی"],
  "sunno":     ["سنو"],
  "maa":     ["ماں"],
  "rehta":     ["رہتا"],
  "rehti":     ["رہتی"],
  "rehte":     ["رہتے"],
  "aye":     ["آئے"],
  "jaana":     ["جانا"],
  "khajoor":     ["کھجور"],
  "azaadi":     ["آزادی"],
  "azadi":     ["آزادی"],
  "wapas":     ["واپس"],
  "mazza":     ["مزہ"],
  "karoon":     ["کروں"],
  "karoonga":     ["کروں گا"],
  "karungi":     ["کروں گی"],
  "isko":     ["اسکو"],
  "usko":     ["اسکو"],
  "aati":     ["آتی"],
  "pasand":     ["پسند"],
  "zaroorat":     ["ضرورت"],
  "zarurat":     ["ضرورت"],
  "farmate":     ["فرماتے"],
  "piye":     ["پیئے"],
  "dho":     ["دھو"],
  "akele":     ["اکیلے"],
  "tanha":     ["تنہا"],
  "maal":     ["مال"],
  "hota":     ["ہوتا"],
  "hoti":     ["ہوتی"],
  "hote":     ["ہوتے"],
  "milega":     ["ملے گا"],
  "milegi":     ["ملے گی"],
  "jaanta":     ["جانتا"],
  "jaanti":     ["جانتی"],
  "jaante":     ["جانتے"],
  "apka":     ["آپ کا"],
  "apki":     ["آپ کی"],
  "sara":     ["سارا"],
  "saari":     ["ساری"],
  "saare":     ["سارے"],
  "jise":     ["جسے"],
  "jiska":     ["جس کا"],
  "kiski":     ["کس کی"],
  "kiska":     ["کس کا"],
  "kisne":     ["کس نے"],
  "kitni":     ["کتنی"],
  "kitne":     ["کتنے"],
  "itti":     ["اتنی"],
  "ita":     ["اتنا"],
  "haan ji":     ["جی ہاں"],
  "jee haan":     ["جی ہاں"],
  "achi":     ["اچھی"],
  "achhe":     ["اچھے"],
  "lagta hai":     ["لگتا ہے"],
  "lagti hai":     ["لگتی ہے"],
  "samjha karo":     ["سمجھا کرو"],
  "pata nahi":     ["پتہ نہیں"],
  "pata nhi":     ["پتہ نہیں"],
  "kuch nahi":     ["کچھ نہیں"],
  "kuch nhi":     ["کچھ نہیں"],
  "kuch nai":     ["کچھ نہیں"],

  // ── Spelling-variant cluster ─────────────────────────────────────────────
  "bohot":    ["بہت"],
  "bhot":     ["بہت"],
  "bohat":    ["بہت"],
  "bhut":     ["بہت"],
  "bahut":    ["بہت"],
  "kesy":     ["کیسے"],
  "kaise":    ["کیسے"],
  "kaisy":    ["کیسے"],
  "hal":      ["حال"],
  "khayal":   ["خیال"],
  "khyal":    ["خیال"],
  "uss":      ["اس"],
  "waisy":    ["ویسے"],
  "waisey":   ["ویسے"],
  "aisy":     ["ایسے"],
  "aase":     ["ایسے"],
  "asay":     ["ایسے"],
  "aise":     ["ایسے"],
  "tumhay":   ["تمہیں"],
  "uskay":    ["اس کے"],
  "mujay":    ["مجھے"],
  "pareshan": ["پریشان"],
  "galti":    ["غلطی"],
  "fursat":   ["فرصت"],

// ── Missing high-frequency words (19A.0c) ───────────────────────────────
  "baje":      ["بجے"],
  "baj":       ["بج"],
  "thak":      ["تھک"],
  "aa":        ["آ"],
  "sakta":     ["سکتا"],
  "sakti":     ["سکتی"],
  "sakte":     ["سکتے"],
  "yaad":      ["یاد"],
  "hoon":      ["ہوں"],
  "zara":      ["ذرا"],
  "zra":       ["ذرا"],
  "jaldi":     ["جلدی"],
  "der":       ["دیر"],
  "baitha":    ["بیٹھا"],
  "baithna":   ["بیٹھنا"],
  "hua":       ["ہوا"],
  "hui":       ["ہوئی"],
  "hue":       ["ہوئے"],
  "ni":        ["نہیں"],
  "nai":       ["نہیں"],
  "nh":        ["نہیں"],
  "Allah":     ["اللہ"],
  "allah":     ["اللہ"],
  "pass":      ["پاس"],
  "hona":      ["ہونا"],
  "yar":       ["یار"],
  "ayi":       ["آئی"],
  "pata":      ["پتہ"],
  "pataa":     ["پتہ"],
  "inshAllah": ["انشاءاللہ"],
  "insha":     ["انشاء"],
  "har":       ["ہر"],
  "sath":      ["ساتھ"],
  "saath":     ["ساتھ"],
  "rishte":    ["رشتے"],
  "maan":      ["مان"],
  "mana":      ["مانا"],
  "mani":      ["مانی"],
  "jaga":      ["جگہ"],
  "jagah":     ["جگہ"],
  "saal":      ["سال"],
  "mahina":    ["مہینہ"],
  "ghanta":    ["گھنٹہ"],
  "ghante":    ["گھنٹے"],
  "minute":    ["minute"],
  "second":    ["second"],
  "hamesha":   ["ہمیشہ"],
  "kabhi nahi":["کبھی نہیں"],
  "zarur":     ["ضرور"],
  "pakka":     ["پکا"],
  "pakki":     ["پکی"],
  "sach":      ["سچ"],
  "sachi":     ["سچی"],
  "jhooth":    ["جھوٹ"],
  "jhuta":     ["جھوٹا"],
  "galat":     ["غلط"],
  "sahi":      ["صحیح"],
  "durust":    ["درست"],
  "bande":     ["بندے"],
  "insaan":    ["انسان"],
  "duniya":    ["دنیا"],
  "mulk":      ["ملک"],
  "sheher":    ["شہر"],
  "gaon":      ["گاؤں"],
  "gali":      ["گلی"],
  "muhalla":   ["محلہ"],
  "raasta":    ["راستہ"],
  "darwaza":   ["دروازہ"],
  "kamra":     ["کمرہ"],
  "bahar":     ["باہر"],
  "andar":     ["اندر"],
  "upar":      ["اوپر"],
  "neeche":    ["نیچے"],
  "aage":      ["آگے"],
  "agay":      ["آگے"],
  "peeche":    ["پیچھے"],
  "dayen":     ["دائیں"],
  "bayen":     ["بائیں"],
  "seedha":    ["سیدھا"],
  "ulta":      ["الٹا"],
  "qareeb":    ["قریب"],
  "door":      ["دور"],
  "tez":       ["تیز"],
  "aahista":   ["آہستہ"],
  "mauka":     ["موقع"],
  "aasaan":    ["آسان"],
  "mumkin":    ["ممکن"],
  "na mumkin": ["ناممکن"],
  "koshish":   ["کوشش"],
  "taqlif":    ["تکلیف"],
  "takleef":   ["تکلیف"],
  "dard":      ["درد"],
  "gham":      ["غم"],
  "pyaar":     ["پیار"],
  "mohabbat":  ["محبت"],
  "dushman":   ["دشمن"],
  "bhai jan":  ["بھائی جان"],
  "ammi":      ["امی"],
  "abba":      ["ابا"],
  "dada":      ["دادا"],
  "dadi":      ["دادی"],
  "nani":      ["نانی"],
  "chacha":    ["چاچا"],
  "mamu":      ["ماموں"],
  "phupho":    ["پھوپھو"],
  "khala":     ["خالہ"],
  "beta":      ["بیٹا"],
  "beti":      ["بیٹی"],
  "bhai bhai": ["بھائی بھائی"],
  "ghar wale": ["گھر والے"],
  "sab log":   ["سب لوگ"],
  "chiz":      ["چیز"],
  "cheez":     ["چیز"],
  "cheezein":  ["چیزیں"],
  "kaam aana": ["کام آنا"],
  "kaam kaaj": ["کام کاج"],
  "faida":     ["فائدہ"],
  "nuqsan":    ["نقصان"],
  "paisa":     ["پیسہ"],
  "paise":     ["پیسے"],
  "rupay":     ["روپے"],
  "rupee":     ["روپے"],
  "talab":     ["تنخواہ"],
  "khaana":    ["کھانا"],
  "doodh":     ["دودھ"],
  "roti":      ["روٹی"],
  "daal":      ["دال"],
  "chawal":    ["چاول"],
  "gosht":     ["گوشت"],
  "murghi":    ["مرغی"],
  "machli":    ["مچھلی"],
  "phal":      ["پھل"],
  "mirch":     ["مرچ"],
  "namak":     ["نمک"],
  "cheeni":    ["چینی"],
  "atta":      ["آٹا"],
  "ghee":      ["گھی"],
  "tel":       ["تیل"],
  "kapra":     ["کپڑا"],
  "joota":     ["جوتا"],
  "jootay":    ["جوتے"],
  "kitab":     ["کتاب"],
  "kagaz":     ["کاغذ"],
  "qalam":     ["قلم"],
  "table":     ["table"],
  "kursi":     ["کرسی"],
  "palang":    ["پلنگ"],
  "gadi":      ["گاڑی"],
  "motor":     ["موٹر"],
  "machine":   ["machine"],
  "mobile":    ["mobile"],
  "phone":     ["phone"],
  "computer":  ["computer"],
  "pankha":    ["پنکھا"],
  "barish":    ["بارش"],
  "dhoop":     ["دھوپ"],
  "hawa":      ["ہوا"],
  "asman":     ["آسمان"],
  "zameen":    ["زمین"],
  "paani":     ["پانی"],
  "naddi":     ["ندی"],
  "darya":     ["دریا"],
  "pahaar":    ["پہاڑ"],
  "khana khana": ["کھانا کھانا"],
  "pani peena":  ["پانی پینا"],
  "neend aana":  ["نیند آنا"],
  "saans":     ["سانس"],
  "awaaz":     ["آواز"],
  "aankhein":  ["آنکھیں"],
  "aankh":     ["آنکھ"],
  "naak":      ["ناک"],
  "kaan":      ["کان"],
  "muh":       ["منہ"],
  "moonh":     ["منہ"],
  "haath":     ["ہاتھ"],
  "pair":      ["پیر"],
  "sar":       ["سر"],
  "peeth":     ["پیٹھ"],
  "seena":     ["سینہ"],
  "dhidha":    ["دیدہ"],
  "aaj bhi":   ["آج بھی"],
  "kal bhi":   ["کل بھی"],
  "phir se":   ["پھر سے"],
  "ek baar":   ["ایک بار"],
  "dobara":    ["دوبارہ"],
  "aakhir":    ["آخر"],
  "aakhir mein": ["آخر میں"],
  "shuruaat":  ["شروعات"],
  "shuru":     ["شروع"],
  "khatam":    ["ختم"],
  "khatm":     ["ختم"],
  "tayyar":    ["تیار"],
  "taiyaar":   ["تیار"],
  "intezar":   ["انتظار"],
  "umeed":     ["امید"],
  "yakin":     ["یقین"],
  "shubar":    ["صبر"],
  "sabr":      ["صبر"],
  "touba":     ["توبہ"],
  "maaf":      ["معاف"],
  "maafi":     ["معافی"],
  "shukria":   ["شکریہ"],
  "khuda hafiz": ["خدا حافظ"],
  "Allah hafiz": ["اللہ حافظ"],
  "salaam":    ["سلام"],
  "assalam":   ["السلام"],
  "walaikum":  ["وعلیکم"],
  "pareshaan": ["پریشان"],
  "chinta":    ["فکر"],
  "fikr":      ["فکر"],
  "zid":       ["ضد"],
  "hasad":     ["حسد"],
  "dhoka":     ["دھوکہ"],
  "bharosa":   ["بھروسہ"],
  "raaz":      ["راز"],
  "baatein":   ["باتیں"],
  "swal":      ["سوال"],
  "sawal":     ["سوال"],
  "jawab":     ["جواب"],
  "matlab":    ["مطلب"],
  "samjhana":  ["سمجھانا"],
  "sunna":     ["سننا"],
  "sochna":    ["سوچنا"],
  "socha":     ["سوچا"],
  "sochu":     ["سوچوں"],
  "pochna":    ["پوچھنا"],
  "boolna":    ["بھولنا"],
  "yaad karna": ["یاد کرنا"],
  "yaad aana": ["یاد آنا"],
  "parwah":    ["پروا"],
  "fikar":     ["فکر"],

  "SubhanAllah":     ["سبحان اللہ"],
  "inshaallah":     ["انشاءاللہ"],
  // ── Religious / cultural ─────────────────────────────────────────────────
  "roza":     ["روزہ"],
  "namaz":    ["نماز"],
  "waqia":    ["واقعہ"],
  "mazar":    ["مزار"],
  "eid":      ["عید"],
  "shair":    ["شعر"],
  "tasalli":  ["تسلی"],
};

/** Look up a token (case-insensitive). Returns null if not in lexicon. */
export function lookupToken(token: string): UrduCandidates | null {
  const lower = token.toLowerCase();
  return (LEXICON[lower] as UrduCandidates | undefined) ?? null;
}

/** Look up with spelling-normalized key (collapse repeated chars). */
export function lookupNormalized(token: string): UrduCandidates | null {
  const lower = token.toLowerCase();
  // Try exact first
  const exact = LEXICON[lower];
  if (exact) return exact as UrduCandidates;
  // Normalize: collapse runs of same letter (e.g. "aaaacha" → "acha")
  const collapsed = lower.replace(/(.)\1{2,}/g, "$1");
  return (LEXICON[collapsed] as UrduCandidates | undefined) ?? null;
}
