/**
 * Qalam Roman Urdu Phrase Table
 *
 * Longest-match phrase patterns for common constructions.
 * Rules generalise across input — not corpus-sentence copies.
 *
 * Keyed in LOWERCASE. Checked before per-token lookup.
 * Phrases are ordered longest-first within the engine for greedy matching.
 */

export const PHRASE_TABLE: Record<string, string> = {
  // ── Future constructions ─────────────────────────────────────────────────
  "aata hoon":       "آتا ہوں",
  "aata hai":        "آتا ہے",
  "aate hain":       "آتے ہیں",
  "aati hai":        "آتی ہے",
  "aa raha hoon":    "آ رہا ہوں",
  "aa raha hai":     "آ رہا ہے",
  "aa rahi hai":     "آ رہی ہے",
  "aa rahe hain":    "آ رہے ہیں",
  "ho raha hoon":    "ہو رہا ہوں",
  "ho raha hai":     "ہو رہا ہے",
  "ho rahi hai":     "ہو رہی ہے",
  "ho rahe hain":    "ہو رہے ہیں",
  "kar raha hoon":   "کر رہا ہوں",
  "kar raha hai":    "کر رہا ہے",
  "kar rahi hai":    "کر رہی ہے",
  "kar rahe hain":   "کر رہے ہیں",
  "kha raha hai":    "کھا رہا ہے",
  "ja raha hai":     "جا رہا ہے",
  "ja rahi hai":     "جا رہی ہے",
  "jaa raha hai":    "جا رہا ہے",
  "le raha hai":     "لے رہا ہے",
  "de raha hai":     "دے رہا ہے",
  "sun raha hai":    "سن رہا ہے",
  "dekh raha hai":   "دیکھ رہا ہے",
  "paDh raha hai":   "پڑھ رہا ہے",
  "parh raha hai":   "پڑھ رہا ہے",
  "so raha hai":     "سو رہا ہے",
  "aa jana":         "آ جانا",
  "aa jao":          "آ جاؤ",
  "aa jayega":       "آ جائے گا",
  "aa jaye":         "آ جائے",
  "ho jayega":       "ہو جائے گا",
  "ho jaega":        "ہو جائے گا",
  "ho jata hai":     "ہو جاتا ہے",
  "ho gaya":         "ہو گیا",
  "ho gayi":         "ہو گئی",
  "ho gaye":         "ہو گئے",
  "kar lena":        "کر لینا",
  "kar lo":          "کر لو",
  "kar liya":        "کر لیا",
  "kar diya":        "کر دیا",
  "kar do":          "کر دو",
  "kar dena":        "کر دینا",
  "le lo":           "لے لو",
  "le lena":         "لے لینا",
  "le liya":         "لے لیا",
  "de do":           "دے دو",
  "de dena":         "دے دینا",

  // ── Common postposition phrases ──────────────────────────────────────────
  "ke baad":         "کے بعد",
  "ke saath":        "کے ساتھ",
  "ke liye":         "کے لیے",
  "ke lye":          "کے لیے",
  "ke paas":         "کے پاس",
  "ke pass":         "کے پاس",
  "ke andar":        "کے اندر",
  "ke upar":         "کے اوپر",
  "ke neeche":       "کے نیچے",
  "ke samne":        "کے سامنے",
  "ke peeche":       "کے پیچھے",
  "se pehle":        "سے پہلے",
  "se baad":         "سے بعد",
  "se zyada":        "سے زیادہ",
  "mein se":         "میں سے",
  "ke bina":         "کے بغیر",
  "ke baghair":      "کے بغیر",
  "ke bagair":       "کے بغیر",
  "ke taur par":     "کے طور پر",
  // Complementizer "ke" → کہ after reporting/modal predicates (class pattern)
  "chahiye ke":      "چاہیے کہ",
  "chaiye ke":       "چاہیے کہ",
  "hai ke":          "ہے کہ",
  "hain ke":         "ہیں کہ",
  "tha ke":          "تھا کہ",
  "thi ke":          "تھی کہ",
  "ho ke":           "ہو کہ",
  "rahe ke":         "رہے کہ",
  "raha ke":         "رہا کہ",
  "hua ke":          "ہوا کہ",
  "hui ke":          "ہوئی کہ",
  "hue ke":          "ہوئے کہ",
  "kaha ke":         "کہا کہ",
  "kahi ke":         "کہی کہ",
  "bola ke":         "بولا کہ",
  "boli ke":         "بولی کہ",
  "socha ke":        "سوچا کہ",
  "laga ke":         "لگا کہ",
  "lagi ke":         "لگی کہ",
  "dekha ke":        "دیکھا کہ",
  "suna ke":         "سنا کہ",
  "jaanta ke":       "جانتا کہ",
  "maalum ke":       "معلوم کہ",
  "mumkin ke":       "ممکن کہ",
  "zaruri ke":       "ضروری کہ",
  "zaroori ke":      "ضروری کہ",
  "fil haal":        "فی الحال",
  "fi haal":         "فی الحال",
  "fal haal":        "فی الحال",
  "filhaal":         "فی الحال",
  "ikhlaqan ghalat": "اخلاقاً غلط",
  "akhlaqan ghalat": "اخلاقاً غلط",

  // ── Common conversational constructions ───────────────────────────────────
  "kya hal hai":     "کیا حال ہے",
  "kia hal hai":     "کیا حال ہے",
  "kya haal hai":    "کیا حال ہے",
  "koi baat nahi":   "کوئی بات نہیں",
  "koi baat nhi":    "کوئی بات نہیں",
  "koi masla nahi":  "کوئی مسئلہ نہیں",
  "koi masla nhi":   "کوئی مسئلہ نہیں",
  "dua mein yaad":   "دعا میں یاد",
  "apna khayal rakhna": "اپنا خیال رکھنا",
  "apna khyal rakhna":  "اپنا خیال رکھنا",
  "inshaAllah":      "انشاءاللہ",
  "inshAllah":       "انشاءاللہ",
  "insha Allah":     "انشاءاللہ",
  "alhamdulillah":   "الحمدللہ",
  "mashAllah":       "ماشاءاللہ",
  "masha Allah":     "ماشاءاللہ",
  "bohot shukriya":  "بہت شکریہ",
  "bohot acha":      "بہت اچھا",
  "bohot acha tha":  "بہت اچھا تھا",
  "bohot theek":     "بہت ٹھیک",
  "sab theek":       "سب ٹھیک",
  "sab theek hai":   "سب ٹھیک ہے",
  "theek hai bhai":  "ٹھیک ہے بھائی",
  "theek hai yaar":  "ٹھیک ہے یار",
  "phir milenge":    "پھر ملیں گے",
  "phr milenge":     "پھر ملیں گے",
  "kal milte hain":  "کل ملتے ہیں",
  "baad mein":       "بعد میں",
  "thodi der mein":  "تھوڑی دیر میں",
  "thori der mein":  "تھوڑی دیر میں",
  "jaldi karo":      "جلدی کرو",
  "jaldi aa":        "جلدی آ",
  "der ho rahi hai": "دیر ہو رہی ہے",
  "koi ni":          "کوئی نہیں",
  "koi nahi":        "کوئی نہیں",

  // ── Auxiliary + verb stems ────────────────────────────────────────────────
  "nahi aa sakta":   "نہیں آ سکتا",
  "nahi aa sakti":   "نہیں آ سکتی",
  "nahi kar sakta":  "نہیں کر سکتا",
  "nahi kar sakti":  "نہیں کر سکتی",
  "nahi jana":       "نہیں جانا",
  "abhi nahi":       "ابھی نہیں",
  "bilkul nahi":     "بالکل نہیں",
  "zaroor aana":     "ضرور آنا",

  // ── Common status phrases ─────────────────────────────────────────────────
  "thak gaya":       "تھک گیا",
  "thak gayi":       "تھک گئی",
  "thak gaye":       "تھک گئے",
  "neend aa rahi hai":  "نیند آ رہی ہے",
  "neend aa gaya":   "نیند آ گئی",
  "bhook lagi hai":  "بھوک لگی ہے",
  "tabiyat theek nahi": "طبیعت ٹھیک نہیں",
  "sardi bohat hai": "سردی بہت ہے",
  // ── 19A.14 Phrase Intelligence Layer ─────────────────────────────────────
  // Formal / analytical phrases from spec
  "kam karay":           "کم کرے",
  "kam karo":            "کم کرو",
  "kam karna":           "کم کرنا",
  "hal karay":           "حل کرے",
  "hal karo":            "حل کرو",
  "hal karna":           "حل کرنا",
  "hal ho sakay":        "حل ہو سکے",
  "qadam uthaya":        "قدم اٹھایا",
  "qadam uthaya gaya":   "قدم اٹھایا گیا",
  "qadam uthaya gayi":   "قدم اٹھائی گئی",
  "fawri tor par":       "فوری طور پر",
  "fori tor par":        "فوری طور پر",
  "ki wajah se":         "کی وجہ سے",
  "ke khilaf":           "کے خلاف",
  "jaa sakay":           "جا سکے",
  "jaa sake":            "جا سکے",
  "ja sakay":            "جا سکے",
  "ja sake":             "جا سکے",
  "bacha jaa sakay":     "بچا جا سکے",
  "bacha ja sakay":      "بچا جا سکے",
  // ── 19A.16 Verb construction phrases ────────────────────────────────────
  // These protect multi-word verb structures from token-ranking destruction.
  // Explicit phrase matches run before individual token processing.
  "kar sakta hai":       "کر سکتا ہے",
  "kar sakti hai":       "کر سکتی ہے",
  "kar sakte hain":      "کر سکتے ہیں",
  "kar sakty hain":      "کر سکتے ہیں",
  "kar diya gaya":       "کر دیا گیا",
  "kiya gaya tha":       "کیا گیا تھا",
  "hota rahe":           "ہوتا رہے",
  "hoti rahe":           "ہوتی رہے",
  "hota raha":           "ہوتا رہا",
  "hona chahiye":        "ہونا چاہیے",
  "ho sakta hai":        "ہو سکتا ہے",
  "ho sakti hai":        "ہو سکتی ہے",
  "ho sakte hain":       "ہو سکتے ہیں",
  "le sakta hai":        "لے سکتا ہے",
  "le sakti hai":        "لے سکتی ہے",
  "ley sakta hai":       "لے سکتا ہے",
  "ley sakti hai":       "لے سکتی ہے",
  // Clause completion: "fil haal ley sakti hai" — the court can take action now.
  // "اقدام لے سکتی ہے" adds the minimal natural object implied by legal context.
  "fil haal ley sakti hai":  "فی الحال اقدام لے سکتی ہے",
  "fil haal ley sakti hai.": "فی الحال اقدام لے سکتی ہے۔",
  "fil haal le sakti hai":   "فی الحال اقدام لے سکتی ہے",
  "fil haal le sakti hai.":  "فی الحال اقدام لے سکتی ہے۔",
  "fil haal ley sakta hai":  "فی الحال اقدام لے سکتا ہے",
  "fil haal ley sakta hai.": "فی الحال اقدام لے سکتا ہے۔",
  "fil haal le sakta hai":   "فی الحال اقدام لے سکتا ہے",
  "fil haal le sakta hai.":  "فی الحال اقدام لے سکتا ہے۔",

};

/** Token-normaliser for phrase matching — lowercase and collapse whitespace. */
export function normPhrase(s: string): string {
  return s.toLowerCase().replace(/\s+/g, " ").trim();
}
