/**
 * Qalam Roman Urdu Phrase Table
 *
 * Longest-match phrase patterns for common constructions.
 * Rules generalise across input — not corpus-sentence copies.
 *
 * Keyed in LOWERCASE. Checked before per-token lookup.
 * Phrases are ordered longest-first within the engine for greedy matching.
 */

export const PHRASE_TABLE: Record<string, string> = {
  // ── Future constructions ─────────────────────────────────────────────────
  "aata hoon":       "آتا ہوں",
  "aata hai":        "آتا ہے",
  "aate hain":       "آتے ہیں",
  "aati hai":        "آتی ہے",
  "aa raha hoon":    "آ رہا ہوں",
  "aa raha hai":     "آ رہا ہے",
  "aa rahi hai":     "آ رہی ہے",
  "aa rahe hain":    "آ رہے ہیں",
  "ho raha hoon":    "ہو رہا ہوں",
  "ho raha hai":     "ہو رہا ہے",
  "ho rahi hai":     "ہو رہی ہے",
  "ho rahe hain":    "ہو رہے ہیں",
  "kar raha hoon":   "کر رہا ہوں",
  "kar raha hai":    "کر رہا ہے",
  "kar rahi hai":    "کر رہی ہے",
  "kar rahe hain":   "کر رہے ہیں",
  "kha raha hai":    "کھا رہا ہے",
  "ja raha hai":     "جا رہا ہے",
  "ja rahi hai":     "جا رہی ہے",
  "jaa raha hai":    "جا رہا ہے",
  "le raha hai":     "لے رہا ہے",
  "de raha hai":     "دے رہا ہے",
  "sun raha hai":    "سن رہا ہے",
  "dekh raha hai":   "دیکھ رہا ہے",
  "paDh raha hai":   "پڑھ رہا ہے",
  "parh raha hai":   "پڑھ رہا ہے",
  "so raha hai":     "سو رہا ہے",
  "aa jana":         "آ جانا",
  "aa jao":          "آ جاؤ",
  "aa jayega":       "آ جائے گا",
  "aa jaye":         "آ جائے",
  "ho jayega":       "ہو جائے گا",
  "ho jaega":        "ہو جائے گا",
  "ho jata hai":     "ہو جاتا ہے",
  "ho gaya":         "ہو گیا",
  "ho gayi":         "ہو گئی",
  "ho gaye":         "ہو گئے",
  "kar lena":        "کر لینا",
  "kar lo":          "کر لو",
  "kar liya":        "کر لیا",
  "kar diya":        "کر دیا",
  "kar do":          "کر دو",
  "kar dena":        "کر دینا",
  "le lo":           "لے لو",
  "le lena":         "لے لینا",
  "le liya":         "لے لیا",
  "de do":           "دے دو",
  "de dena":         "دے دینا",

  // ── Common postposition phrases ──────────────────────────────────────────
  "ke baad":         "کے بعد",
  "ke saath":        "کے ساتھ",
  "ke liye":         "کے لیے",
  "ke lye":          "کے لیے",
  "ke paas":         "کے پاس",
  "ke pass":         "کے پاس",
  "ke andar":        "کے اندر",
  "ke upar":         "کے اوپر",
  "ke neeche":       "کے نیچے",
  "ke samne":        "کے سامنے",
  "ke peeche":       "کے پیچھے",
  "se pehle":        "سے پہلے",
  "se baad":         "سے بعد",
  "se zyada":        "سے زیادہ",
  "mein se":         "میں سے",
  "ke bina":         "کے بغیر",
  "ke taur par":     "کے طور پر",

  // ── Common conversational constructions ───────────────────────────────────
  "kya hal hai":     "کیا حال ہے",
  "kia hal hai":     "کیا حال ہے",
  "kya haal hai":    "کیا حال ہے",
  "koi baat nahi":   "کوئی بات نہیں",
  "koi baat nhi":    "کوئی بات نہیں",
  "koi masla nahi":  "کوئی مسئلہ نہیں",
  "koi masla nhi":   "کوئی مسئلہ نہیں",
  "dua mein yaad":   "دعا میں یاد",
  "apna khayal rakhna": "اپنا خیال رکھنا",
  "apna khyal rakhna":  "اپنا خیال رکھنا",
  "inshaAllah":      "انشاءاللہ",
  "inshAllah":       "انشاءاللہ",
  "insha Allah":     "انشاءاللہ",
  "alhamdulillah":   "الحمدللہ",
  "mashAllah":       "ماشاءاللہ",
  "masha Allah":     "ماشاءاللہ",
  "bohot shukriya":  "بہت شکریہ",
  "bohot acha":      "بہت اچھا",
  "bohot acha tha":  "بہت اچھا تھا",
  "bohot theek":     "بہت ٹھیک",
  "sab theek":       "سب ٹھیک",
  "sab theek hai":   "سب ٹھیک ہے",
  "theek hai bhai":  "ٹھیک ہے بھائی",
  "theek hai yaar":  "ٹھیک ہے یار",
  "phir milenge":    "پھر ملیں گے",
  "phr milenge":     "پھر ملیں گے",
  "kal milte hain":  "کل ملتے ہیں",
  "baad mein":       "بعد میں",
  "thodi der mein":  "تھوڑی دیر میں",
  "thori der mein":  "تھوڑی دیر میں",
  "jaldi karo":      "جلدی کرو",
  "jaldi aa":        "جلدی آ",
  "der ho rahi hai": "دیر ہو رہی ہے",
  "koi ni":          "کوئی نہیں",
  "koi nahi":        "کوئی نہیں",

  // ── Auxiliary + verb stems ────────────────────────────────────────────────
  "nahi aa sakta":   "نہیں آ سکتا",
  "nahi aa sakti":   "نہیں آ سکتی",
  "nahi kar sakta":  "نہیں کر سکتا",
  "nahi kar sakti":  "نہیں کر سکتی",
  "nahi jana":       "نہیں جانا",
  "abhi nahi":       "ابھی نہیں",
  "bilkul nahi":     "بالکل نہیں",
  "zaroor aana":     "ضرور آنا",

  // ── Common status phrases ─────────────────────────────────────────────────
  "thak gaya":       "تھک گیا",
  "thak gayi":       "تھک گئی",
  "thak gaye":       "تھک گئے",
  "neend aa rahi hai":  "نیند آ رہی ہے",
  "neend aa gaya":   "نیند آ گئی",
  "bhook lagi hai":  "بھوک لگی ہے",
  "tabiyat theek nahi": "طبیعت ٹھیک نہیں",
  "sardi bohat hai": "سردی بہت ہے",
};

/** Token-normaliser for phrase matching — lowercase and collapse whitespace. */
export function normPhrase(s: string): string {
  return s.toLowerCase().replace(/\s+/g, " ").trim();
}
