export const QURAN_TRANSLATIONS_SEGMENT_05 = {
  "40:60": { ur: "اور تمہارا پروردگار فرماتا ہے: مجھے پکارو، میں تمہاری دعائیں قبول کروں گا، جو لوگ از راہ تکبر میری عبادت سے منہ موڑتے ہیں یقینا وہ ذلیل ہو کر عنقریب جہنم میں داخل ہوں گے۔", en: "Your Lord has said, ‘Call Me, and I will hear you!’ Indeed those who are disdainful of My worship will enter hell in utter humility." },
  "42:23": { ur: "یہ وہ بات ہے جس کی اللہ اپنے ان بندوں کو خوشخبری دیتا ہے جو ایمان لاتے ہیں اور اعمال صالح بجا لاتے ہیں۔ ، کہدیجئے: میں اس (تبلیغ رسالت) پر تم سے کوئی اجرت نہیں مانگتا سوائے قریب ترین رشتہ داروں کی محبت کے اور جو کوئی نیکی کمائے ہم اس کے لیے اس نیکی میں اچھا اضافہ کرتے ہیں، اللہ یقینا بڑا بخشنے والا، قدردان ہے۔", en: "That is the good news Allah gives to His servants who have faith and do righteous deeds! Say, ‘I do not ask you any reward for it except love of [my] relatives.’ Whoever performs a good deed, We shall enhance for him its goodness. Indeed Allah is all-forgiving, all-appreciative." },
  "42:37": { ur: "اور جو بڑے بڑے گناہوں اور بے حیائی کی باتوں سے پرہیز کرتے ہیں اور جب انہیں غصہ آئے تو معاف کر دیتے ہیں۔", en: "—Those who avoid major sins and indecencies, and forgive when angered;" },
  "46:15": { ur: "اور ہم نے انسان کو اپنے ماں باپ پر احسان کرنے کا حکم دیا، اس کی ماں نے تکلیف سہ کر اسے پیٹ میں اٹھائے رکھا اور تکلیف اٹھا کر اسے جنا اور اس کے حمل اور دودھ چھڑانے میں تیس ماہ لگ جاتے ہیں، یہاں تک کہ جب وہ رشد کامل کو پہنچا اور چالیس سال کا ہو گیا تو کہنے لگا: پروردگار! مجھے توفیق دے کہ میں تیری اس نعمت کا شکر ادا کروں جس سے تو نے مجھے اور میرے والدین کو نوازا اور یہ کہ میں ایسا نیک عمل کروں جسے تو پسند کرے اور میری اولاد کو میرے لیے صالح بنا دے، میں تیری طرف رجوع کرتا ہوں اور بے شک میں مسلمانوں میں سے ہوں۔", en: "We have enjoined man to be kind to his parents. His mother has carried him in travail, and bore him in travail, and his gestation and weaning take thirty months. When he comes of age and reaches forty years, he says, ‘My Lord! Inspire me to give thanks for Your blessing with which You have blessed me and my parents, and that I may do righteous deeds which may please You, and invest my descendants with righteousness. Indeed I have turned to you in penitence, and I am one of the muslims.’" },
  "49:12": { ur: "اے ایمان والو! بہت سے گمانوں سے بچو، بعض گمان یقینا گناہ ہیں اور تجسس بھی نہ کیا کرو اور تم میں سے کوئی بھی ایک دوسرے کی غیبت نہ کرے، کیا تم میں سے کوئی اس بات کو پسند کرے گا کہ اپنے مرے ہوئے بھائی کا گوشت کھائے؟ اس سے تو تم نفرت کرتے ہو اور اللہ سے ڈرو، اللہ یقینا بڑا توبہ قبول کرنے والا، مہربان ہے۔", en: "O you who have faith! Avoid much suspicion. Indeed some suspicions are sins. And do not spy on or backbite one another. Will any of you love to eat the flesh of his dead brother? You would hate it. And be wary of Allah; indeed Allah is all-clement, all-merciful." },
  "50:18": { ur: "(انسان) کوئی بات زبان سے نہیں نکالتا مگر یہ کہ اس کے پاس ایک نگران تیار ہوتا ہے۔", en: "he says no word but that there is a ready observer beside him." },
  "53:39": { ur: "اور یہ کہ انسان کو صرف وہی ملتا ہے جس کی وہ سعی کرتا ہے۔", en: "and that nothing belongs to man except what he strives for," },
  "58:11": { ur: "اے ایمان والو! جب تم سے کہا جائے کہ مجلسوں میں کشادگی پیدا کرو تو کشادگی پیدا کر دیا کرو، اللہ تمہیں کشادگی دے گا اور جب تم سے کہا جائے: اٹھ جاؤ تو اٹھ جایا کرو، تم میں سے جو لوگ ایمان لے آئے اور وہ لوگ جنہیں علم دیا گیا ہے ان کے درجات کو اللہ بلند فرمائے گا اور جو کچھ تم کرتے ہو اللہ اس سے خوب باخبر ہے۔", en: "O you who have faith! When you are told, ‘Make room,’ in sittings, then do make room; Allah will make room for you. And when you are told, ‘Rise up!’ Do rise up. Allah will raise those of you who have faith and those who have been given knowledge in rank, and Allah is well aware of what you do." },
  "59:7": { ur: "اللہ نے ان بستی والوں کے مال سے جو کچھ بھی اپنے رسول کی آمدنی قرار دیا ہے وہ اللہ اور رسول اور قریب ترین رشتہ داروں اور یتیموں اور مسکینوں اور مسافروں کے لیے ہے تاکہ وہ مال تمہارے دولت مندوں کے درمیان ہی گردش نہ کرتا رہے اور رسول جو تمہیں دے دیں وہ لے لو اور جس سے روک دیں اس سے رک جاؤ اور اللہ کا خوف کرو، اللہ یقینا شدید عذاب دینے والا ہے۔", en: "The spoils that Allah gave to His Apostle from the people of the townships, are for Allah and the Apostle, the relatives and the orphans, the needy and the traveller, so that they do not circulate among the rich among you. Take whatever the Apostle gives you, and relinquish whatever he forbids you, and be wary of Allah. Indeed Allah is severe in retribution." },
  "59:18": { ur: "اے ایمان والو! اللہ سے ڈرو اور ہر شخص کو یہ دیکھنا چاہیے کہ اس نے کل (روز قیامت) کے لیے کیا بھیجا ہے اور اللہ سے ڈرو، جو کچھ تم کرتے ہو، اللہ یقینا اس سے خوب با خبر ہے۔", en: "O you who have faith! Be wary of Allah, and let every soul consider what it sends ahead for tomorrow, and be wary of Allah. Allah is indeed well aware of what you do" },
} as const;
