export const QURAN_TRANSLATIONS_SEGMENT_03 = {
  "9:20": { ur: "جو لوگ ایمان لائے اور ہجرت کی اور اپنے اموال سے اور اپنی جانوں سے راہ خدا میں جہاد کیا وہ اللہ کے نزدیک نہایت عظیم درجہ رکھتے ہیں اور وہی لوگ کامیاب ہیں۔", en: "Those who have believed and migrated, and waged jiha\u0081d in the way of Allah with their possessions and persons have a greater rank near Allah, and it is they who are the triumphant." },
  "9:119": { ur: "اے ایمان والو! اللہ سے ڈرو اور سچوں کے ساتھ ہوجاؤ۔", en: "O you who have faith! Be wary of Allah, and be with the Truthful." },
  "11:6": { ur: "اور زمین پر چلنے والا کو ئی ایسا نہیں جس کا رزق اللہ کے ذمے نہ ہو اور وہ جانتا ہے کہ اس کی جائے قرار کہاں ہے اور عارضی جگہ کہاں ہے، سب کچھ روشن کتاب میں موجود ہے۔", en: "There is no animal on the earth, but that its sustenance lies with Allah, and He knows its [enduring] abode and its temporary place of lodging. Everything is in a manifest Book." },
  "14:7": { ur: "اور (اے مسلمانو! یاد کرو) جب تمہارے پروردگار نے خبردار کیا کہ اگر تم شکر کرو تو میں تمہیں ضرور زیادہ دوں گا اور اگر ناشکری کرو تو میرا عذاب یقینا سخت ہے۔", en: "And when your Lord proclaimed, ‘If you are grateful, I will surely enhance you [in blessing], but if you are ungrateful, My punishment is indeed severe.’" },
  "16:90": { ur: "یقینا اللہ عدل اور احسان اور قرابتداروں کو (ان کا حق) دینے کا حکم دیتا ہے اور بے حیائی اور برائی اور زیادتی سے منع کرتا ہے۔ وہ تمہیں نصیحت کرتا ہے شاید تم نصیحت قبول کرو۔", en: "Indeed Allah enjoins justice and kindness and generosity towards relatives, and He forbids indecency, wrong, and aggression. He advises you, so that you may take admonition." },
  "17:9": { ur: "یہ قرآن یقینا اس راہ کی ہدایت کرتا ہے جو بالکل سیدھی ہے اور ان مومنین کو جو نیک اعمال بجا لاتے ہیں یہ بشارت دیتا ہے کہ ان کے لیے بڑا اجر ہے۔", en: "Indeed this Qur’an guides to what is most upright, and gives the good news to the faithful who do righteous deeds that there is a great reward for them." },
  "17:23": { ur: "اور آپ کے پروردگار نے فیصلہ کر دیا ہے کہ تم اس کے سوا کسی کی بندگی نہ کرو اور والدین کے ساتھ نیکی کرو، اگر ان میں سے ایک یا دونوں تمہارے پاس ہوں اور بڑھاپے کو پہنچ جائیں تو انہیں اف تک نہ کہنا اور انہیں نہ جھڑکنا بلکہ ان سے عزت و تکریم کے ساتھ بات کرنا۔", en: "Your Lord has decreed that you shall not worship anyone except Him, and [He has enjoined] kindness to parents. Should they reach old age at your side —one of them or both— do not say to them, ‘Fie!’ And do not chide them, but speak to them noble words." },
  "17:24": { ur: "اور مہر و محبت کے ساتھ ان کے آگے انکساری کا پہلو جھکائے رکھو اور دعا کرو: پروردگارا! ان پر رحم فرماجس طرح انہوں نے مجھے پچپن میں (شفقت سے) پالا تھا۔", en: "Lower the wing of humility to them, out of mercy, and say, ‘My Lord! Have mercy on them, just as they reared me when I was [a] small [child]!’" },
  "18:13": { ur: "ہم آپ کو ان کا حقیقی واقعہ سناتے ہیں، وہ کئی جوان تھے جو اپنے رب پر ایمان لے آئے تھے اور ہم نے انہیں مزید ہدایت دی۔", en: "We relate to you their account in truth. They were indeed youths who had faith in their Lord, and We had enhanced them in guidance," },
  "27:62": { ur: "کون ہے جو مضطرب کی فریاد سنتا ہے جب وہ اسے پکارتا ہے اور اس کی تکلیف دور کرتا ہے اور تمہیں زمین میں جانشین بناتا ہے؟ کیا اللہ کے ساتھ کوئی اور معبود بھی ہے؟ تم لوگ بہت کم نصیحت حاصل کرتے ہو۔", en: "Is He who answers the call of the distressed [person] when he invokes Him and removes his distress, and makes you the earth’s successors. . . ? What! Is there a god besides Allah? Little is the admonition that you take." },
} as const;
