export const QURAN_TRANSLATIONS_SEGMENT_01 = {
  "2:124": { ur: "اور (وہ وقت یاد رکھو) جب ابراہیم کو ان کے رب نے چند کلمات سے آزمایا اور انہوں نے انہیں پورا کر دکھایا، ارشاد ہوا: میں تمہیں لوگوں کا امام بنانے والا ہوں، انہوں نے کہا: اور میری اولاد سے بھی؟ ارشاد ہوا: میرا عہد ظالموں کو نہیں پہنچے گا۔", en: "And when his Lord tested Abraham with certain words, and he fulfilled them, He said, ‘I am making you the Imam of mankind.’ Said he, ‘And from among my descendants?’ He said, ‘My pledge does not extend to the unjust.’" },
  "2:152": { ur: "لہٰذا تم مجھے یاد رکھو میں تمہیں یاد رکھوں گا اور میرا شکر ادا کرو اور میری ناشکری نہ کرو۔", en: "Remember Me, and I will remember you, and thank Me, and do not be ungrateful to Me." },
  "2:153": { ur: "اے ایمان والو! صبر اور نماز سے مدد لو، اللہ یقینا صبر کرنے والوں کے ساتھ ہے۔", en: "O you who have faith! Take recourse in patience and prayer; indeed Allah is with the patient." },
  "2:155": { ur: "اور ہم تمہیں کچھ خوف، بھوک اور جان و مال اور ثمرات (کے نقصانات) سے ضرور آزمائیں گے اور آپ ان صبر کرنے والوں کو خوشخبری سنا دیجیے۔", en: "We will surely test you with a measure of fear and hunger and a loss of wealth, lives, and fruits; and give good news to the patient" },
  "2:186": { ur: "اور جب میرے بندے آپ سے میرے متعلق سوال کریں تو (کہدیں کہ) میں (ان سے) قریب ہوں، دعا کرنے والاجب مجھے پکارتا ہے تو میں اس کی دعا قبول کرتا ہوں، پس انہیں بھی چاہیے کہ وہ میری دعوت پر لبیک کہیں اور مجھ پر ایمان لائیں تاکہ وہ راہ راست پر رہیں۔", en: "When My servants ask you about Me, [tell them that] I am indeed nearmost. I answer the supplicant’s call when he calls Me. So let them respond to Me, and let them have faith in Me, so that they may fare rightly." },
  "2:267": { ur: "اے ایمان والو! جو مال تم کماتے ہو اور جو کچھ ہم نے تمہارے لیے زمین سے نکالا ہے اس میں سے عمدہ حصہ (راہ خدا میں) خرچ کرو اور اس میں سے ردی چیز دینے کا قصد ہی نہ کرو اور (اگر کوئی وہی تمہیں دے تو) تم خود اسے لیناگوارا نہ کرو گے مگر یہ کہ چشم پوشی کر جاؤ اور جان رکھو کہ اللہ بڑا بے نیاز اور لائق ستائش ہے۔", en: "O you who have faith! Spend of the good things you have earned, and of what We bring forth for you from the earth, and do not be of the mind to give the bad part of it, for you yourselves would not take it, unless you overlook it. And know that Allah is all-sufficient, all-laudable." },
  "3:33": { ur: "بے شک اللہ نے آدم، نوح، آل ابراہیم اور آل عمران کو تمام عالمین پر برگزیدہ فرمایا ہے۔", en: "Indeed Allah chose Adam and Noah, and the progeny of Abraham and the progeny of Imran above all the nations;" },
  "3:102": { ur: "اے ایمان والو! اللہ کا خوف کرو جیسا کہ اس کا خوف کرنے کا حق ہے اور جان نہ دینا مگر اس حال میں کہ تم مسلم ہو۔", en: "O you who have faith! Be wary of Allah with the wariness due to Him and do not die except as muslims." },
  "3:134": { ur: "(ان متقین کے لیے) جو خواہ آسودگی میں ہوں یا تنگی میں ہر حال میں خرچ کرتے ہیں اور غصے کو پی جاتے ہیں اور لوگوں سے درگزر کرتے ہیں اور اللہ احسان کرنے والوں کو دوست رکھتا ہے۔", en: "—those who spend in ease and adversity, and suppress their anger, and excuse [the faults of] the people, and Allah loves the virtuous;" },
  "3:159": { ur: "(اے رسول) یہ مہر الٰہی ہے کہ آپ ان کے لیے نرم مزاج واقع ہوئے اور اگر آپ تندخو اور سنگدل ہوتے تو یہ لوگ آپ کے پاس سے منتشر ہو جاتے، پس ان سے درگزر کریں اور ان کے لیے مغفرت طلب کریں اور معاملات میں ان سے مشورہ کر لیا کریں پھر جب آپ عزم کر لیں تو اللہ پر بھروسہ کریں، بے شک اللہ بھروسہ کرنے والوں کو پسند کرتاہے۔", en: "It is by Allah’s mercy that you are gentle to them; and had you been harsh and hardhearted, surely they would have scattered from around you. So excuse them, and plead for forgiveness for them, and consult them in the affairs, and once you are resolved, put your trust in Allah. Indeed Allah loves those who trust in Him." },
} as const;
