export const QURAN_TRANSLATIONS_SEGMENT_06 = {
  "65:2": { ur: "پس جب عورتیں اپنی عدت پوری کرنے کو آئیں تو انہیں اچھی طرح سے (اپنے عقد میں) رکھو یا انہیں اچھے طریقے سے علیحدہ کر دو اور اپنوں میں سے دو صاحبان عدل کو گواہ بناؤ اور اللہ کی خاطر درست گواہی دو، یہ وہ باتیں ہیں جن کی تمہیں نصیحت کی جاتی ہے ہر اس شخص کے لیے جو اللہ اور روز آخرت پر ایمان رکھتا ہو اور جو اللہ سے ڈرتا رہے اللہ اس کے لیے (مشکلات سے) نکلنے کا راستہ بنا دیتا ہے،", en: "Then, when they have completed their term, either retain them honourably or separate from them honourably, and take the witness of two fair men from among yourselves, and bear witness for the sake of Allah. To [comply with] this is advised whoever believes in Allah and the Last Day. And whoever is wary of Allah, He shall make a way out for him," },
  "65:3": { ur: "اور اسے ایسی جگہ سے رزق دیتا ہے جہاں سے وہ سوچ بھی نہ سکتا ہو اور جو اللہ پر بھروسہ کرتا ہے پس اس کے لیے اللہ کافی ہے، اللہ اپنا حکم پورا کرنے والا ہے، بتحقیق اللہ نے ہر چیز کے لیے ایک اندازہ مقرر کیا ہے۔", en: "and provide for him from whence he does not reckon. And whoever puts his trust in Allah, He will suffice him. Indeed Allah carries through His command. Certainly Allah has set a measure for everything." },
  "66:6": { ur: "اے ایمان والو! اپنے آپ کو اور اپنے اہل و عیال کو اس آگ سے بچاؤ جس کا ایندھن انسان اور پتھر ہوں گے، اس پر تندخو اور سخت مزاج فرشتے مقرر ہیں جو اللہ کے حکم کی نافرمانی نہیں کرتے اور جو حکم انہیں ملتا ہے اسے بجا لاتے ہیں۔", en: "O you who have faith! Save yourselves and your families from a Fire whose fuel is people and stones, over which are [assigned] angels, severe and mighty, who do not disobey whatever Allah has commanded them, and carry out what they are commanded." },
  "66:8": { ur: "اے ایمان والو! اللہ کے آگے توبہ کرو خالص توبہ، بعید نہیں کہ اللہ تم سے تمہارے گناہ دور کر دے اور تمہیں ایسی جنتوں میں داخل کر دے جن کے نیچے نہریں بہتی ہوں گی، اس دن اللہ نہ اپنے نبی کو رسوا کرے گا اور نہ ہی ان لوگوں کو جو اس کے ساتھ ایمان لائے ہیں، ان کا نور ان کے آگے اور ان کی دائیں طرف دوڑ رہا ہو گا اور وہ دعا کر رہے ہوں گے: اے ہمارے پروردگار! ہمارا نور ہمارے لیے پورا کر دے اور ہم سے درگزر فرما، بے شک تو ہر چیز پر قادر ہے۔", en: "O you who have faith! Repent to Allah with sincere repentance! Maybe your Lord will absolve you of your misdeeds and admit you into gardens with streams running in them, on the day when Allah will not let the Prophet down and the faithful who are with him. Their light will move swiftly before them and on their right. They will say, ‘Our Lord! Perfect our light for us, and forgive us! Indeed You have power over all things.’" },
  "71:10": { ur: "اور کہا: اپنے پروردگار سے معافی مانگو، وہ یقینا بڑا معاف کرنے والا ہے۔", en: "telling [them]: ‘‘Plead to your Lord for forgiveness. Indeed He is all-forgiver." },
  "71:11": { ur: "وہ تم پر آسمان سے خوب بارش برسائے گا،", en: "He will send for you abundant rains from the sky," },
  "71:12": { ur: "وہ اموال اور اولاد کے ذریعے تمہاری مدد کرے گا اور تمہارے لیے باغات بنائے گا اور تمہارے لیے نہریں بنائے گا۔", en: "and aid you with wealth and sons, and provide you with gardens and provide you with streams." },
  "76:8": { ur: "اور اپنی خواہش کے باوجود مسکین، یتیم اور اسیر کو کھانا کھلاتے ہیں۔", en: "They give food, for the love of Him, to the needy, the orphan and the prisoner," },
  "76:9": { ur: "(وہ ان سے کہتے ہیں) ہم تمہیں صرف اللہ (کی رضا) کے لیے کھلا رہے ہیں، ہم تم سے نہ تو کوئی معاوضہ چاہتے ہیں اور نہ ہی شکرگزاری۔", en: "[saying,] ‘We feed you only for the sake of Allah. We do not want any reward from you nor any thanks." },
  "112:1": { ur: "کہدیجیے: وہ اللہ ایک ہے۔", en: "Say, ‘He is Allah, the One." },
} as const;
