export const QURAN_TRANSLATIONS_SEGMENT_04 = {
  "29:60": { ur: "اور بہت سے جانور ایسے ہیں جو اپنا رزق اٹھائے نہیں پھرتے، اللہ ہی انہیں رزق دیتا ہے اور تمہیں بھی اور وہ بڑا سننے والا، جاننے والا ہے۔", en: "How many an animal there is that does not carry its own provision. Allah provides for it, and for you, and He is the All-hearing, the All-knowing." },
  "30:21": { ur: "اور یہ اس کی نشانیوں میں سے ہے کہ اس نے تمہارے لیے تمہاری ہی جنس سے ازواج پیدا کیے تاکہ تم ان سے سکون حاصل کرو اور اس نے تمہارے مابین محبت اور مہربانی پیدا کی، غور و فکر کرنے والوں کے لیے یقینا ان میں نشانیاں ہیں۔", en: "And of His signs is that He created for you mates from your own selves that you may take comfort in them, and He ordained affection and mercy between you. There are indeed signs in that for a people who reflect." },
  "31:12": { ur: "اور بتحقیق ہم نے لقمان کو حکمت سے نوازا کہ اللہ کا شکر کریں اور جو شکر کرتا ہے وہ اپنے (فائدے کے) لیے شکر کرتا ہے اور جو ناشکری کرتا ہے تو اللہ یقینابے نیاز، لائق ستائش ہے۔", en: "Certainly We gave Luqman wisdom, saying, ‘Give thanks to Allah; and whoever gives thanks, gives thanks only for his own sake. And whoever is ungrateful, [let him know that] Allah is indeed all-sufficient, all-laudable.’" },
  "31:13": { ur: "اور جب لقمان نے اپنے بیٹے کو نصیحت کرتے ہوئے کہا: اے بیٹا! اللہ کے ساتھ کسی کو شریک نہ ٹھہرانا، یقینا شرک بہت بڑا ظلم ہے۔", en: "When Luqman said to his son, as he advised him: ‘O my son! Do not ascribe any partners to Allah. Polytheism is indeed a great injustice.’" },
  "31:14": { ur: "اور ہم نے انسان کو اس کے والدین کے بارے میں نصیحت کی، اس کی ماں نے کمزوری پر کمزوری سہ کر اسے (پیٹ میں) اٹھایا اور اس کے دودھ چھڑانے کی مدت دو سال ہے (نصیحت یہ کہ) میرا شکر بجا لاؤ اور اپنے والدین کا بھی (شکر ادا کرو آخر میں) بازگشت میری طرف ہے۔", en: "We have enjoined man concerning his parents: His mother carried him through weakness upon weakness, and his weaning takes two years. Give thanks to Me and to your parents. To Me is the return." },
  "33:21": { ur: "بتحقیق تمہارے لیے اللہ کے رسول میں بہترین نمونہ ہے، ہر اس شخص کے لیے جو اللہ اور روز آخرت کی امید رکھتا ہو اور کثرت سے اللہ کا ذکر کرتا ہو۔", en: "In the Apostle of Allah there is certainly for you a good exemplar, for those who look forward to Allah and the Last Day, and remember Allah greatly." },
  "33:33": { ur: "اور اپنے گھروں میں جم کر بیٹھی رہو اور قدیم جاہلیت کی طرح اپنے آپ کو نمایاں کرتی نہ پھرو نیز نماز قائم کرو اور زکوٰۃ دیا کرو اور اللہ اور اس کے رسول کی اطاعت کرو، اللہ کا ارادہ بس یہی ہے ہر طرح کی ناپاکی کو اہل بیت! آپ سے دور رکھے اور آپ کو ایسے پاکیزہ رکھے جیسے پاکیزہ رکھنے کا حق ہے۔", en: "Stay in your houses and do not display your finery with the display of the former [days of ] ignorance. Maintain the prayer and pay the zakat and obey Allah and His Apostle. Indeed Allah desires to repel all impurity from you, O People of the Household, and purify you with a thorough purification." },
  "39:9": { ur: "(مشرک بہتر ہے) یا وہ شخص جو رات کی گھڑیوں میں سجدے اور قیام کی حالت میں عبادت کرتا ہے، آخرت سے ڈرتا ہے اور اپنے رب کی رحمت سے امید لگائے رکھتا ہے، کہدیجئے: کیا جاننے والے اور نہ جاننے والے یکساں ہو سکتے ہیں؟ بے شک ت تو صرف عقل والے ہی قبول کرتے ہیں۔", en: "Is he who supplicates in the watches of the night, prostrating and standing, apprehensive of the Hereafter and expecting the mercy of his Lord . . . ? Say, ‘Are those who know equal to those who do not know?’ Only those who possess intellect take admonition." },
  "39:36": { ur: "کیا اللہ اپنے بندے کے لیے کافی نہیں ہے؟ اور یہ لوگ آپ کو اس (اللہ) کے علاوہ دوسروں سے ڈراتے ہیں جب کہ اللہ جسے گمراہ کر دے اسے راہ دکھانے والا کوئی نہیں ہے۔", en: "Does not Allah suffice [to defend] His servant? They would frighten you of others than Him. Yet whomever Allah leads astray, has no guide," },
  "39:53": { ur: "کہدیجئے: اے میرے بندو! جنہوں نے اپنی جانوں پر زیادتی کی اللہ کی رحمت سے مایوس نہ ہونا، یقینا اللہ تمام گناہوں کو معاف فرماتا ہے، وہ یقینا بڑا معاف کرنے والا، مہربان ہے۔", en: "Say [that Allah declares,] ‘O My servants who have committed excesses against their own souls, do not despair of the mercy of Allah. Indeed Allah will forgive all sins. Indeed He is the All-forgiving, the All-merciful." },
} as const;
