export const QURAN_TRANSLATIONS_SEGMENT_02 = {
  "3:185": { ur: "ہر جاندار کو موت کا ذائقہ چکھنا ہے اور تمہیں تو قیامت کے دن پورا اجر و ثواب ملے گا (در حقیقت) کامیاب وہ ہے جسے آتش جہنم سے بچا کرجنت میں داخل کر دیا جائے، (ورنہ) دنیاوی زندگی تو صرف فریب کا سامان ہے۔", en: "Every soul shall taste death, and you will indeed be paid your full rewards on the Day of Resurrection. Whoever is delivered from the Fire and admitted to paradise has certainly succeeded. The life of this world is nothing but the wares of delusion." },
  "3:200": { ur: "اے ایمان والو! صبر سے کام لو استقامت کا ظاہر کرو، مورچہ بند رہو اور اللہ سے ڈرو تاکہ تم کامیابی حاصل کر سکو۔", en: "O you who have faith! Be patient, stand firm, and close [your] ranks, and be wary of Allah so that you may be felicitous." },
  "4:59": { ur: "اے ایمان والو! اللہ کی اطاعت کرو اور رسول کی اور تم میں سے جو صاحبان امر ہیں ان کی اطاعت کرو پھر اگر تمہارے درمیان کسی بات میں نزاع ہو جائے تو اس سلسلے میں اللہ اور رسول کی طرف رجوع کرو اگر تم اللہ اور روز آخرت پر ایمان رکھتے ہو۔ یہی بھلائی ہے اور اس کا انجام بھی بہتر ہو گا۔", en: "O you who have faith! Obey Allah and obey the Apostle and those vested with authority among you. And if you dispute concerning anything, refer it to Allah and the Apostle, if you have faith in Allah and the Last Day. That is better and more favourable in outcome." },
  "4:135": { ur: "اے ایمان والو! انصاف کے سچے داعی بن جاؤ اور اللہ کے لیے گواہ بنو اگرچہ تمہاری ذات یا تمہارے والدین اور رشتہ داروں کے خلاف ہی کیوں نہ ہو، اگر کوئی امیر یا فقیر ہے تو اللہ ان کا بہتر خیرخواہ ہے، لہٰذا تم خواہش نفس کی وجہ سے عدل نہ چھوڑو اور اگر تم نے کج بیانی سے کام لیا یا (گواہی دینے سے) پہلوتہی کی تو جان لو کہ اللہ تمہارے اعمال سے یقینا خوب باخبر ہے۔", en: "O you who have faith! Be maintainers of justice and witnesses for the sake of Allah, even if it should be against yourselves or [your] parents and near relatives, and whether it be [someone] rich or poor, for Allah has a greater right over them. So do not follow [your] desires, lest you should be unfair, and if you distort [the testimony] or disregard [it], Allah is indeed well aware of what you do." },
  "5:8": { ur: "اے ایمان والو! اللہ کے لیے بھرپور قیام کرنے والے اور انصاف کے ساتھ گواہی دینے والے بن جاؤ اور کسی قوم کی دشمنی تمہاری بے انصافی کا سبب نہ بنے، (ہر حال میں) عدل کرو! یہی تقویٰ کے قریب ترین ہے اور اللہ سے ڈرو، بے شک اللہ تمہارے اعمال سے خوب باخبر ہے۔", en: "O you who have faith! Be maintainers, as witnesses for the sake of Allah, of justice, and ill feeling for a people should never lead you to be unfair. Be fair; that is nearer to Godwariness, and be wary of Allah. Allah is indeed well aware of what you do." },
  "5:55": { ur: "تمہارا ولی تو صرف اللہ اور اس کا رسول اور وہ اہل ایمان ہیں جو نماز قائم کرتے ہیں اور حالت رکوع میں زکوٰۃ دیتے ہیں۔", en: "Your guardian is only Allah, His Apostle, and the faithful who maintain the prayer and give the zakat while bowing down." },
  "6:124": { ur: "اور جب کوئی آیت ان کے پاس آتی ہے تو کہتے ہیں: ہم اس وقت تک نہیں مانیں گے جب تک ہمیں بھی وہ چیز نہ دی جائے جو اللہ کے رسولوں کو دی گئی ہے، اللہ (ہی) بہتر جانتا ہے کہ اپنی رسالت کہاں رکھے، جن لوگوں نے جرم کا ارتکاب کیا انہیں ان کی مکاریوں کی پاداش میں اللہ کے ہاں عنقریب ذلت اور شدید عذاب کا سامنا کرنا ہوگا۔", en: "And when a sign comes to them, they say, ‘We will not believe until we are given the like of what was given to Allah’s apostles.’ Allah knows best where to place His apostleship! Soon the guilty will be visited by a degradation before Allah and a severe punishment because of the plots they used to devise." },
  "7:55": { ur: "اپنے رب کی بارگاہ میں دعا کرو عاجزی اور خاموشی کے ساتھ، بے شک وہ تجاوز کرنے والوں کو دوست نہیں رکھتا۔", en: "Supplicate your Lord, beseechingly and secretly. Indeed He does not like the transgressors." },
  "8:2": { ur: "مومن تو صرف وہ ہیں کہ جب اللہ کا ذکر کیا جاتا ہے تو ان کے دل کانپ جاتے ہیں اور جب انہیں اس کی آیات پڑھ کر سنائی جاتی ہیں تو ان کے ایمان میں اضافہ ہوتا ہے اور وہ اپنے رب پر بھروسہ کرتے ہیں۔", en: "The faithful are only those whose hearts tremble [with awe] when Allah is mentioned, and when His signs are recited to them, they increase their faith, and who put their trust in their Lord," },
  "8:25": { ur: "اور اس فتنے سے بچو جس کی لپیٹ میں تم میں سے صرف ظلم کرنے والے ہی نہیں بلکہ (سب) آئیں گے اور یہ جان لو کہ اللہ سخت عذاب دینے والا ہے۔", en: "And beware of a punishment which shall not visit the wrongdoers among you exclusively, and know that Allah is severe in retribution." },
} as const;
