export type ShiaCalendarRegion = "all" | "pk" | "in" | "ir";

export type ShiaCalendarEvent = {
  id: string;
  month: "ربیع الثانی";
  day: number;
  dayLabel?: string;
  title: string;
  note?: string;
  /** Region-specific date/usage. Omit for events treated as generally applicable. */
  regions?: readonly ShiaCalendarRegion[];
  sourceId: string;
  sourceLabel: string;
  sourceUrl: string;
  sourceCapturedAt: string;
};

export const RABI_AL_THANI_1448_EVENTS: readonly ShiaCalendarEvent[] = [
  {
    id: "r2-01-tawwabin",
    month: "ربیع الثانی",
    day: 1,
    title: "قیامِ توابین",
    note: "65ھ",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-02-08-askari-week",
    month: "ربیع الثانی",
    day: 2,
    dayLabel: "2 تا 8",
    title: "ہفتۂ بزرگداشتِ ولادت امام حسن عسکریؑ",
    note: "2 تا 8 ربیع الثانی",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-03-jurjan",
    month: "ربیع الثانی",
    day: 3,
    title: "امام حسن عسکریؑ کا جرجان کا تاریخی سفر",
    note: "255ھ",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-04-abdolazim",
    month: "ربیع الثانی",
    day: 4,
    title: "ولادت حضرت عبدالعظیم حسنیؑ",
    note: "173ھ",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-06-hisham",
    month: "ربیع الثانی",
    day: 6,
    title: "ہلاکتِ ہشام بن عبدالملک",
    note: "125ھ",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-06-askari-report",
    month: "ربیع الثانی",
    day: 6,
    title: "ولادت امام حسن عسکریؑ",
    note: "232ھ؛ ایک روایت",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-08-askari",
    month: "ربیع الثانی",
    day: 8,
    title: "ولادت امام حسن عسکریؑ",
    note: "232ھ؛ ایک معروف تقویمی روایت",
    sourceId: "shiastudies-rabi-al-thani",
    sourceLabel: "مجمع جهانی شیعه شناسی",
    sourceUrl: "https://shiastudies.com/fa/%D9%87%D8%B4%D8%AA%D9%85-%D8%B1%D8%A8%DB%8C%D8%B9-%D8%A7%D9%84%D8%AB%D8%A7%D9%86%DB%8C/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-08-zahra-40",
    month: "ربیع الثانی",
    day: 8,
    title: "شہادت حضرت فاطمہ زہراؑ",
    note: "40 روز والی روایت",
    sourceId: "shiastudies-rabi-al-thani",
    sourceLabel: "مجمع جهانی شیعه شناسی",
    sourceUrl: "https://shiastudies.com/fa/%D9%87%D8%B4%D8%AA%D9%85-%D8%B1%D8%A8%DB%8C%D8%B9-%D8%A7%D9%84%D8%AB%D8%A7%D9%86%DB%8C/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-10-fatimiyya-first",
    month: "ربیع الثانی",
    day: 10,
    dayLabel: "10 تا 13",
    title: "ایامِ بزرگداشت شہادت حضرت فاطمہ زہراؑ",
    note: "فاطمیہ اول؛ روایت 45 روز",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-10-masuma",
    month: "ربیع الثانی",
    day: 10,
    title: "وفات حضرت فاطمہ معصومہؑ",
    note: "201ھ",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-10-askari-pk",
    month: "ربیع الثانی",
    day: 10,
    title: "ولادت امام حسن عسکریؑ",
    note: "232ھ؛ پاکستان میں رائج تاریخ",
    regions: ["pk"],
    sourceId: "shareekatulhussain-pk-1448",
    sourceLabel: "مسجد و امام بارگاہ شریکۃ الحسینؑ — کراچی",
    sourceUrl: "https://www.shareekatulhussain.com/?month=9&previewDate=2026-09-23",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-10-askari-alkafeel",
    month: "ربیع الثانی",
    day: 10,
    title: "ولادت امام حسن عسکریؑ",
    note: "232ھ؛ 10 ربیع الثانی کی روایت",
    sourceId: "alkafeel-10-rabi-al-thani",
    sourceLabel: "الکفیل انٹرنیشنل نیٹ ورک",
    sourceUrl: "https://alkafeel.net/news/index?id=9634&lang=ur",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-10-askari-shia-org",
    month: "ربیع الثانی",
    day: 10,
    title: "ولادت امام حسن عسکریؑ",
    note: "232ھ؛ 10 ربیع الثانی کی تاریخی نسبت",
    sourceId: "al-shia-10-rabi-al-thani",
    sourceLabel: "الشیعہ اردو",
    sourceUrl: "https://ur.al-shia.org/%D8%AD%D8%B6%D8%B1%D8%AA-%D8%A7%D9%85%D8%A7%D9%85-%D8%AD%D8%B3%D9%86-%D8%B9%D8%B3%DA%A9%D8%B1%DB%8C%D8%B9/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-10-askari-baltistan",
    month: "ربیع الثانی",
    day: 10,
    title: "ولادت امام حسن عسکریؑ",
    note: "232ھ؛ 10 ربیع الثانی کی نسبت، ایک پاکستانی مذہبی ماخذ",
    regions: ["pk"],
    sourceId: "ya-mahdi-baltistan-askari",
    sourceLabel: "مؤسسه علمی، فرهنگی امام زمان (عج) بلتستان",
    sourceUrl: "https://ya-mahdi786.blogfa.com/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-12-umayyad",
    month: "ربیع الثانی",
    day: 12,
    title: "انقراض بنی امیہ اور آغاز حکومت بنی عباس",
    note: "132ھ",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-13-fatimiyya-45",
    month: "ربیع الثانی",
    day: 13,
    title: "شہادت حضرت فاطمہ زہراؑ",
    note: "45 روز والی روایت؛ ابن شہر آشوب کی نسبت",
    sourceId: "shiastudies-rabi-al-thani",
    sourceLabel: "مجمع جهانی شیعه شناسی",
    sourceUrl: "https://shiastudies.com/fa/%D8%B3%DB%8C%D8%B2%D8%AF%D9%87%D9%85-%D8%B1%D8%A8%DB%8C%D8%B9-%D8%A7%D9%84%D8%AB%D8%A7%D9%86%DB%8C/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-13-mohaghegh-hilli",
    month: "ربیع الثانی",
    day: 13,
    title: "ارتحال محقق حلیؒ",
    note: "676ھ؛ صاحب شرائع الاسلام",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-14-mukhtar",
    month: "ربیع الثانی",
    day: 14,
    title: "قیامِ مختارؒ",
    note: "66ھ",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-20-fatwa-1920",
    month: "ربیع الثانی",
    day: 20,
    title: "فتوائے انقلابِ 1920ء کے اجرا کی یاد",
    note: "1337ھ؛ میرزا محمد تقی شیرازیؒ",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-22-musa-mubarqa",
    month: "ربیع الثانی",
    day: 22,
    title: "وفات موسیٰ مبرقعؒ",
    note: "296ھ",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-25-muawiya-yazid",
    month: "ربیع الثانی",
    day: 25,
    title: "معاویہ بن یزید کا خلافت سے کنارہ کش ہونا",
    note: "64ھ",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-28-amini",
    month: "ربیع الثانی",
    day: 28,
    title: "ارتحال علامہ عبدالحسین امینیؒ",
    note: "1390ھ؛ مؤلف الغدیر",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
  {
    id: "r2-29-30-khalid",
    month: "ربیع الثانی",
    day: 29,
    dayLabel: "29/30",
    title: "ہلاکت خالد بن ولید",
    note: "21 یا 22ھ؛ ماخذ میں 29/30 ربیع الثانی",
    sourceId: "shiawaves-rabi-al-thani-1448",
    sourceLabel: "شبکہ امام حسین / شیعہ تقویم",
    sourceUrl: "https://shiawaves.com/persian/shia-calendar/",
    sourceCapturedAt: "2026-10-02",
  },
] as const;
