/**
 * Khateeb Studio Urdu language guard.
 *
 * User-facing Urdu must not depend on English vocabulary.  Legacy content may
 * still contain mixed terminology internally; this normalizer removes those
 * terms at the data boundary while source strings are progressively cleaned.
 *
 * Long phrases are intentionally replaced before single words.
 */
const REPLACEMENTS: readonly [RegExp, string][] = [
  [/research dossier/gi, "تحقیقی دستاویز"],
  [/ready-to-use study material/gi, "خطابت کے لیے تیار علمی مواد"],
  [/source-backed/gi, "ماخذ سے ثابت شدہ"],
  [/full transcript/gi, "مکمل مکتوب خطاب"],
  [/archived collection/gi, "محفوظ مجموعۂ مجالس"],
  [/central thesis/gi, "مرکزی مقدمہ"],
  [/governing question/gi, "مرکزی سوال"],
  [/ready speaking flow/gi, "قابلِ بیان منبری ترتیب"],
  [/decision-making/gi, "فیصلہ سازی"],
  [/relational modeling/gi, "تعلقات میں عملی نمونہ"],
  [/skill-building/gi, "مہارت کی تربیت"],
  [/reaction delay for moral clarity/gi, "اخلاقی وضوح کے لیے ردِّعمل میں توقف"],
  [/strong feeling/gi, "شدید جذبہ"],
  [/family framing/gi, "خاندانی زاویۂ بیان"],
  [/dining table/gi, "کھانے کی میز"],
  [/concrete behavioral advice/gi, "واضح عملی ہدایت"],
  [/practical segment/gi, "عملی حصہ"],
  [/trainable skill/gi, "قابلِ تربیت مہارت"],
  [/inner energy/gi, "اندرونی قوت"],
  [/patience training/gi, "صبر کی تربیت"],
  [/repeated micro-practices/gi, "بار بار کی جانے والی چھوٹی مشقوں"],
  [/methodological caution/gi, "منہجی احتیاط"],
  [/source criticism/gi, "ماخذی تنقید"],
  [/structural reasoning/gi, "ساختی استدلال"],
  [/spiritual formation/gi, "روحانی تربیت"],
  [/coherent structure/gi, "مربوط ساخت"],
  [/transformative leader/gi, "تغییر آفرین رہنما"],
  [/dormant potential/gi, "پوشیدہ صلاحیت"],
  [/hidden capacities/gi, "پوشیدہ صلاحیتیں"],
  [/historical admiration/gi, "تاریخی تحسین"],
  [/practical correction/gi, "عملی اصلاح"],
  [/biography quiz/gi, "محض سوانحی معلومات"],
  [/lived relationship/gi, "عملی تعلق"],
  [/succession debate/gi, "جانشینی کی بحث"],
  [/life decisions/gi, "زندگی کے فیصلے"],
  [/historical succession/gi, "تاریخی جانشینی"],
  [/political authority/gi, "سیاسی اقتدار"],
  [/devotional love/gi, "عقیدتی محبت"],
  [/trustworthy guidance/gi, "معتبر ہدایت"],
  [/theological necessity/gi, "کلامی ضرورت"],
  [/knowledge alone/gi, "محض علم"],
  [/chosen scholarly treatment/gi, "منتخب علمی توضیح"],
  [/practical suspension/gi, "عملی تعطل"],
  [/self-centered wish list/gi, "صرف اپنی حاجات کی فہرست"],
  [/information transfer/gi, "اطلاع پہنچانا"],
  [/relationship activation/gi, "تعلق کو زندہ کرنا"],
  [/heart-dependence/gi, "دل کا حقیقی اعتماد"],
  [/quality over quantity/gi, "مقدار کے بجائے کیفیت"],
  [/character curriculum/gi, "کردار سازی کا نصاب"],
  [/spiritual mirror/gi, "روحانی آئینہ"],
  [/self-diagnosis/gi, "اپنے باطن کی پہچان"],
  [/operating skill/gi, "زندگی کی عملی مہارت"],
  [/social media/gi, "سماجی ذرائع ابلاغ"],
  [/homework/gi, "گھر کا سبق"],
  [/framework/gi, "علمی خاکہ"],
  [/evidence/gi, "دلیل"],
  [/confidence/gi, "اعتماد"],
  [/taxonomy/gi, "درجہ بندی"],
  [/reference/gi, "حوالہ"],
  [/simultaneously/gi, "بیک وقت"],
  [/society/gi, "معاشرہ"],
  [/knowledge/gi, "علم"],
  [/continuity/gi, "تسلسل"],
  [/functions/gi, "ذمہ داریاں"],
  [/headings/gi, "عنوانات"],
  [/mobilize/gi, "متحرک کرنا"],
  [/teacher/gi, "معلم"],
  [/direction/gi, "سمت"],
  [/leadership/gi, "قیادت"],
  [/unfold/gi, "ابھارنا"],
  [/historical/gi, "تاریخی"],
  [/practical/gi, "عملی"],
  [/source/gi, "ماخذ"],
  [/framing/gi, "زاویۂ بیان"],
  [/doctrine/gi, "عقیدہ"],
  [/qualities/gi, "اوصاف"],
  [/pattern/gi, "نمونہ"],
  [/meaningful/gi, "بامعنی"],
  [/ruler/gi, "حکمران"],
  [/mufti/gi, "فقیہ"],
  [/saint/gi, "روحانی پیشوا"],
  [/dimension/gi, "پہلو"],
  [/smoker/gi, "تمباکو نوش"],
  [/smoking/gi, "تمباکو نوشی"],
  [/stand/gi, "موقف"],
  [/sacrifice/gi, "قربانی"],
  [/slogan/gi, "نعرہ"],
  [/biography/gi, "سوانح"],
  [/commitment/gi, "عزم"],
  [/dossier/gi, "تحقیقی دستاویز"],
  [/passive/gi, "غیر فعال"],
  [/action/gi, "اقدام"],
  [/suppression/gi, "جذبات دبانا"],
  [/ego/gi, "انا"],
  [/material/gi, "مواد"],
  [/contemporary/gi, "موجودہ"],
  [/challenge/gi, "سوال اٹھانا"],
  [/capacity/gi, "صلاحیت"],
  [/character/gi, "کردار"],
  [/abstract/gi, "تجریدی"],
  [/lecture/gi, "نصیحت"],
  [/model/gi, "نمونہ"],
  [/training/gi, "تربیت"],
  [/exercise/gi, "مشق"],
  [/approach/gi, "زاویۂ بیان"],
  [/steps/gi, "مراحل"],
  [/struggle/gi, "کشمکش"],
  [/intentionally/gi, "دانستہ"],
  [/silence/gi, "خاموشی"],
  [/synthesis/gi, "جامع نتیجہ"],
  [/agency/gi, "اخلاقی اختیار"],
  [/disciplined/gi, "منضبط"],
  [/impulse/gi, "فوری جذبہ"],
  [/message/gi, "پیغام"],
  [/confrontation/gi, "ٹکراؤ"],
  [/controlled/gi, "مغلوب"],
  [/reaction/gi, "ردِّعمل"],
  [/family/gi, "خاندان"],
  [/angle/gi, "زاویہ"],
  [/practice/gi, "مشق"],
  [/develop/gi, "پختہ کرنا"],
  [/flow/gi, "ترتیب"],
  [/index/gi, "موضوعاتی فہرست"],
  [/indexed/gi, "موضوعاتی طور پر شامل"],
  [/verified/gi, "مصدقہ"],
  [/verification/gi, "تصدیق"],
  [/ingest/gi, "متن شامل"],
  [/corpus/gi, "علمی ذخیرہ"],
  [/curated pack/gi, "مرتب شدہ مجموعہ"],
  [/Qalam/gi, "قلم"],
  [/thesis/gi, "مرکزی مقدمہ"],
  [/qualification-before-appointment/gi, "منصب سے پہلے ثابت شدہ اہلیت"],
  [/moral impossibility/gi, "اخلاقی طور پر صدور کا ناممکن ہونا"],
  [/empirical observation/gi, "مشاہداتی علم"],
  [/stronger certainty/gi, "زیادہ قطعی یقین"],
  [/real human condition/gi, "حقیقی انسانی حالت"],
  [/moral virtue/gi, "اخلاقی فضیلت"],
  [/Qur'anic correction/gi, "قرآنی اصلاح"],
  [/ethical bridge/gi, "اخلاقی ربط"],
  [/inaccessible metaphysics/gi, "ناقابلِ فہم مابعد الطبیعی بحث"],
  [/hierarchy of guidance/gi, "مراتبِ ہدایت"],
  [/distinct divine office/gi, "الگ الٰہی منصب"],
  [/intellectual staircase/gi, "مسلسل علمی زینہ"],
  [/magic shield/gi, "خودکار حفاظتی حصار"],
  [/perfected qualification/gi, "کامل اہلیت"],
  [/real human life/gi, "حقیقی انسانی زندگی"],
  [/self-mastery/gi, "ضبطِ نفس"],
  [/ordinary moral life/gi, "روزمرہ اخلاقی زندگی"],
  [/ethical implication/gi, "اخلاقی نتیجہ"],
  [/arbitrary lottery/gi, "بے اصول انتخاب"],
  [/hidden conduct/gi, "پوشیدہ کردار"],
  [/physical inability/gi, "جسمانی عدمِ قدرت"],
  [/character-incompatible/gi, "کردار کے منافی"],
  [/social pressure/gi, "سماجی دباؤ"],
  [/moral grandeur/gi, "اخلاقی عظمت"],
  [/theological/gi, "کلامی"],
  [/moral qualification/gi, "اخلاقی اہلیت"],
  [/divine offices/gi, "الٰہی مناصب"],
  [/divine office/gi, "الٰہی منصب"],
  [/divine appointment/gi, "الٰہی تقرر"],
  [/shared principle/gi, "مشترک اصول"],
  [/shared/gi, "مشترک"],
  [/principle/gi, "اصول"],
  [/definition/gi, "تعریف"],
  [/empirical/gi, "مشاہداتی"],
  [/observation/gi, "مشاہدہ"],
  [/certainty/gi, "یقین"],
  [/weakness/gi, "کمزوری"],
  [/perfection/gi, "کمال"],
  [/analogy/gi, "مثال"],
  [/compatible/gi, "ہم آہنگ"],
  [/comparison/gi, "تقابل"],
  [/objection/gi, "اعتراض"],
  [/lesson/gi, "سبق"],
  [/hierarchy/gi, "مراتب"],
  [/distinct/gi, "جداگانہ"],
  [/argue/gi, "استدلال"],
  [/distinction/gi, "امتیاز"],
  [/qualification/gi, "اہلیت"],
  [/transition/gi, "ربط"],
  [/isolated/gi, "الگ تھلگ"],
  [/series/gi, "سلسلۂ مجالس"],
  [/intellectual/gi, "علمی"],
  [/future/gi, "آئندہ"],
  [/answer/gi, "جواب"],
  [/tension/gi, "اشکال"],
  [/mechanical/gi, "جبری و خودکار"],
  [/human life/gi, "انسانی زندگی"],
  [/hunger/gi, "بھوک"],
  [/anger/gi, "غصہ"],
  [/desire/gi, "خواہش"],
  [/pain/gi, "درد"],
  [/obedience/gi, "اطاعت"],
  [/moral/gi, "اخلاقی"],
  [/real/gi, "حقیقی"],
  [/human/gi, "انسانی"],
  [/condition/gi, "حالت"],
  [/virtue/gi, "فضیلت"],
  [/binary question/gi, "دو رخی سوال"],
  [/conceptual resolution/gi, "تصوری حل"],
  [/case study/gi, "مثالی مطالعہ"],
  [/classification/gi, "درجہ بندی"],
  [/succession/gi, "جانشینی"],
  [/family of offices/gi, "مناصب کا سلسلہ"],
  [/decisive text/gi, "فیصلہ کن آیت"],
  [/synonym/gi, "ہم معنی منصب"],
  [/authority/gi, "اختیار"],
  [/argumentative flow/gi, "استدلالی ترتیب"],
  [/pedagogical style/gi, "تدریسی انداز"],
  [/ready-made answer/gi, "تیار جواب"],
  [/knowledge observer/gi, "مشاہدہ کرنے والے کا علم"],
  [/reality/gi, "حقیقت"],
  [/conclusion/gi, "نتیجہ"],
  [/description/gi, "بیان"],
  [/claim/gi, "دعویٰ"],
  [/construction/gi, "تشکیل"],
  [/voluntary obedience/gi, "ارادی اطاعت"],
  [/alternative action/gi, "متبادل عمل"],
  [/moral achievement/gi, "اخلاقی فضیلت"],
  [/linguistic observation/gi, "لسانی مشاہدہ"],
  [/mechanical programming/gi, "جبری ساخت"],
  [/comparative merit/gi, "تقابلی فضیلت"],
  [/human embodiment/gi, "انسانی جسمانی حالت"],
  [/worldly pressure/gi, "دنیاوی دباؤ"],
  [/broader framework/gi, "وسیع علمی خاکہ"],
  [/pronouns/gi, "ضمائر"],
  [/common ground/gi, "مشترک بنیاد"],
  [/fine distinction/gi, "دقیق فرق"],
  [/opposite misunderstandings/gi, "دو متضاد غلط فہمیاں"],
  [/human relevance/gi, "انسانی معنویت"],
  [/concrete/gi, "واضح"],
  [/metaphysical property/gi, "مابعد الطبیعی صفت"],
  [/self-government/gi, "نفس پر حکمرانی"],
  [/inner discipline/gi, "باطنی ضبط"],
  [/historical manifestations/gi, "تاریخی مظاہر"],
  [/ethical aspiration/gi, "اخلاقی نصب العین"],
  [/language/gi, "زبان"],
  [/illustration/gi, "مثال"],
  [/guidance/gi, "ہدایت"],
  [/offices/gi, "مناصب"],
  [/Qur'anic case study/gi, "قرآنی مثال"],
  [/environment of temptation/gi, "آزمائش کا ماحول"],
  [/voluntary sinlessness/gi, "ارادی بے گناہی"],
  [/practical ethical bridge/gi, "عملی اخلاقی ربط"],
  [/answer-dump/gi, "جوابوں کا انبار"],
  [/divine knowledge/gi, "علمِ الٰہی"],
  [/infallibility/gi, "عصمت"],
  [/anthropological/gi, "انسان شناسانہ"],
  [/reductionism/gi, "تخفیف"],
  [/sinlessness/gi, "بے گناہی"],
  [/compatibility/gi, "ہم آہنگی"],
  [/incompatible/gi, "ناسازگار"],
  [/observational/gi, "مشاہداتی"],
  [/defeasible/gi, "قابلِ نقض"],
  [/experiential/gi, "تجربی"],
  [/explanatory/gi, "توضیحی"],
  [/rhetorical/gi, "خطابی"],
  [/credentials/gi, "اسناد"],
  [/architecture/gi, "ساخت"],
  [/compulsion/gi, "جبر"],
  [/possibilities/gi, "امکانات"],
  [/distinguish/gi, "امتیاز کرنا"],
  [/linguistic/gi, "لسانی"],
  [/morphology/gi, "صرف و نحو"],
  [/suitability/gi, "موزونیت"],
  [/achievement/gi, "بلند مقام"],
  [/temptation/gi, "آزمائش"],
  [/environment/gi, "ماحول"],
  [/voluntary/gi, "ارادی"],
  [/angelic/gi, "فرشتوں والی"],
  [/theology/gi, "علم کلام"],
  [/argument/gi, "استدلال"],
  [/selection/gi, "انتخاب"],
  [/correction/gi, "اصلاح"],
  [/conceptual/gi, "تصوری"],
  [/comparative/gi, "تقابلی"],
  [/arbitrary/gi, "بے اصول"],
  [/reinforce/gi, "مضبوط کرنا"],
  [/relevant/gi, "متعلق"],
  [/directly/gi, "براہِ راست"],
  [/guarantee/gi, "ضمانت"],
  [/category/gi, "قسم"],
  [/logical/gi, "منطقی"],
  [/lexical/gi, "لغوی"],
  [/method/gi, "طریقہ"],
  [/history/gi, "تاریخ"],
  [/public/gi, "عوامی"],
  [/power/gi, "قدرت"],
  [/social/gi, "سماجی"],
  [/ethical/gi, "اخلاقی"],
  [/divine/gi, "الٰہی"],
  [/claims/gi, "دعوے"],
  [/stronger/gi, "زیادہ مضبوط"],
  [/translate/gi, "منتقل کرنا"],
  [/technique/gi, "طریقِ کار"],
  [/bearing/gi, "دلالت"],
  [/ordinary/gi, "عام"],
  [/decoration/gi, "زینت"],
  [/bridge/gi, "ربط"],
  [/life/gi, "زندگی"],
  [/sequence/gi, "سلسلہ"],
  [/dump/gi, "انبار"],
];

export function pureKhateebUrdu(text: string): string {
  const ordered = [...REPLACEMENTS].sort((a, b) => b[0].source.length - a[0].source.length);
  return text
    .split("\n")
    .map((line) => {
      let value = line;
      for (const [pattern, replacement] of ordered) {
        const bounded = new RegExp(`(?<![A-Za-z])(?:${pattern.source})(?![A-Za-z])`, pattern.flags);
        value = value.replace(bounded, replacement);
      }
      return value.replace(/[^\S\n]{2,}/g, " ").trim();
    })
    .join("\n");
}

export function hasLatinWord(text: string): boolean {
  return /[A-Za-z]{2,}/.test(text);
}
