/**
 * Khateeb Studio Urdu language guard.
 *
 * User-facing Urdu must not depend on English vocabulary.  Legacy content may
 * still contain mixed terminology internally; this normalizer removes those
 * terms at the data boundary while source strings are progressively cleaned.
 *
 * Long phrases are intentionally replaced before single words.
 */
const REPLACEMENTS: readonly [RegExp, string][] = [
  [/research dossier/gi, "تحقیقی دستاویز"],
  [/ready-to-use study material/gi, "خطابت کے لیے تیار علمی مواد"],
  [/source-backed/gi, "ماخذ سے ثابت شدہ"],
  [/full transcript/gi, "مکمل مکتوب خطاب"],
  [/archived collection/gi, "محفوظ مجموعۂ مجالس"],
  [/central thesis/gi, "مرکزی مقدمہ"],
  [/governing question/gi, "مرکزی سوال"],
  [/ready speaking flow/gi, "قابلِ بیان منبری ترتیب"],
  [/decision-making/gi, "فیصلہ سازی"],
  [/relational modeling/gi, "تعلقات میں عملی نمونہ"],
  [/skill-building/gi, "مہارت کی تربیت"],
  [/reaction delay for moral clarity/gi, "اخلاقی وضوح کے لیے ردِّعمل میں توقف"],
  [/strong feeling/gi, "شدید جذبہ"],
  [/family framing/gi, "خاندانی زاویۂ بیان"],
  [/dining table/gi, "کھانے کی میز"],
  [/concrete behavioral advice/gi, "واضح عملی ہدایت"],
  [/practical segment/gi, "عملی حصہ"],
  [/trainable skill/gi, "قابلِ تربیت مہارت"],
  [/inner energy/gi, "اندرونی قوت"],
  [/patience training/gi, "صبر کی تربیت"],
  [/repeated micro-practices/gi, "بار بار کی جانے والی چھوٹی مشقوں"],
  [/methodological caution/gi, "منہجی احتیاط"],
  [/source criticism/gi, "ماخذی تنقید"],
  [/structural reasoning/gi, "ساختی استدلال"],
  [/spiritual formation/gi, "روحانی تربیت"],
  [/coherent structure/gi, "مربوط ساخت"],
  [/transformative leader/gi, "تغییر آفرین رہنما"],
  [/dormant potential/gi, "پوشیدہ صلاحیت"],
  [/hidden capacities/gi, "پوشیدہ صلاحیتیں"],
  [/historical admiration/gi, "تاریخی تحسین"],
  [/practical correction/gi, "عملی اصلاح"],
  [/biography quiz/gi, "محض سوانحی معلومات"],
  [/lived relationship/gi, "عملی تعلق"],
  [/succession debate/gi, "جانشینی کی بحث"],
  [/life decisions/gi, "زندگی کے فیصلے"],
  [/historical succession/gi, "تاریخی جانشینی"],
  [/political authority/gi, "سیاسی اقتدار"],
  [/devotional love/gi, "عقیدتی محبت"],
  [/trustworthy guidance/gi, "معتبر ہدایت"],
  [/theological necessity/gi, "کلامی ضرورت"],
  [/knowledge alone/gi, "محض علم"],
  [/chosen scholarly treatment/gi, "منتخب علمی توضیح"],
  [/practical suspension/gi, "عملی تعطل"],
  [/self-centered wish list/gi, "صرف اپنی حاجات کی فہرست"],
  [/information transfer/gi, "اطلاع پہنچانا"],
  [/relationship activation/gi, "تعلق کو زندہ کرنا"],
  [/heart-dependence/gi, "دل کا حقیقی اعتماد"],
  [/quality over quantity/gi, "مقدار کے بجائے کیفیت"],
  [/character curriculum/gi, "کردار سازی کا نصاب"],
  [/spiritual mirror/gi, "روحانی آئینہ"],
  [/self-diagnosis/gi, "اپنے باطن کی پہچان"],
  [/operating skill/gi, "زندگی کی عملی مہارت"],
  [/social media/gi, "سماجی ذرائع ابلاغ"],
  [/homework/gi, "گھر کا سبق"],
  [/framework/gi, "علمی خاکہ"],
  [/evidence/gi, "دلیل"],
  [/confidence/gi, "اعتماد"],
  [/taxonomy/gi, "درجہ بندی"],
  [/reference/gi, "حوالہ"],
  [/simultaneously/gi, "بیک وقت"],
  [/society/gi, "معاشرہ"],
  [/knowledge/gi, "علم"],
  [/continuity/gi, "تسلسل"],
  [/functions/gi, "ذمہ داریاں"],
  [/headings/gi, "عنوانات"],
  [/mobilize/gi, "متحرک کرنا"],
  [/teacher/gi, "معلم"],
  [/direction/gi, "سمت"],
  [/leadership/gi, "قیادت"],
  [/unfold/gi, "ابھارنا"],
  [/historical/gi, "تاریخی"],
  [/practical/gi, "عملی"],
  [/source/gi, "ماخذ"],
  [/framing/gi, "زاویۂ بیان"],
  [/doctrine/gi, "عقیدہ"],
  [/qualities/gi, "اوصاف"],
  [/pattern/gi, "نمونہ"],
  [/meaningful/gi, "بامعنی"],
  [/ruler/gi, "حکمران"],
  [/mufti/gi, "فقیہ"],
  [/saint/gi, "روحانی پیشوا"],
  [/dimension/gi, "پہلو"],
  [/smoker/gi, "تمباکو نوش"],
  [/smoking/gi, "تمباکو نوشی"],
  [/stand/gi, "موقف"],
  [/sacrifice/gi, "قربانی"],
  [/slogan/gi, "نعرہ"],
  [/biography/gi, "سوانح"],
  [/commitment/gi, "عزم"],
  [/dossier/gi, "تحقیقی دستاویز"],
  [/passive/gi, "غیر فعال"],
  [/action/gi, "اقدام"],
  [/suppression/gi, "جذبات دبانا"],
  [/ego/gi, "انا"],
  [/material/gi, "مواد"],
  [/contemporary/gi, "موجودہ"],
  [/challenge/gi, "سوال اٹھانا"],
  [/capacity/gi, "صلاحیت"],
  [/character/gi, "کردار"],
  [/abstract/gi, "تجریدی"],
  [/lecture/gi, "نصیحت"],
  [/model/gi, "نمونہ"],
  [/training/gi, "تربیت"],
  [/exercise/gi, "مشق"],
  [/approach/gi, "زاویۂ بیان"],
  [/steps/gi, "مراحل"],
  [/struggle/gi, "کشمکش"],
  [/intentionally/gi, "دانستہ"],
  [/silence/gi, "خاموشی"],
  [/synthesis/gi, "جامع نتیجہ"],
  [/agency/gi, "اخلاقی اختیار"],
  [/disciplined/gi, "منضبط"],
  [/impulse/gi, "فوری جذبہ"],
  [/message/gi, "پیغام"],
  [/confrontation/gi, "ٹکراؤ"],
  [/controlled/gi, "مغلوب"],
  [/reaction/gi, "ردِّعمل"],
  [/family/gi, "خاندان"],
  [/angle/gi, "زاویہ"],
  [/practice/gi, "مشق"],
  [/develop/gi, "پختہ کرنا"],
  [/flow/gi, "ترتیب"],
  [/index/gi, "موضوعاتی فہرست"],
  [/indexed/gi, "موضوعاتی طور پر شامل"],
  [/verified/gi, "مصدقہ"],
  [/verification/gi, "تصدیق"],
  [/ingest/gi, "متن شامل"],
  [/corpus/gi, "علمی ذخیرہ"],
  [/curated pack/gi, "مرتب شدہ مجموعہ"],
  [/Qalam/gi, "قلم"],
  [/thesis/gi, "مرکزی مقدمہ"],
];

export function pureKhateebUrdu(text: string): string {
  const ordered = [...REPLACEMENTS].sort((a, b) => b[0].source.length - a[0].source.length);
  return text
    .split("\n")
    .map((line) => {
      let value = line;
      for (const [pattern, replacement] of ordered) {
        const bounded = new RegExp(`(?<![A-Za-z])(?:${pattern.source})(?![A-Za-z])`, pattern.flags);
        value = value.replace(bounded, replacement);
      }
      return value.replace(/[^\S\n]{2,}/g, " ").trim();
    })
    .join("\n");
}

export function hasLatinWord(text: string): boolean {
  return /[A-Za-z]{2,}/.test(text);
}
